package com.nexaflow.domain.risk

import com.nexaflow.domain.capability.CapabilityId
import com.nexaflow.domain.capability.CapabilityRiskLevel
import com.nexaflow.domain.capability.PrivilegeLevel
import kotlinx.serialization.Serializable

/**
 * Risk classification for every action type.
 *
 * Risk level determines:
 *  - Whether the action can auto-execute (LOW)
 *  - Whether the user is prompted (HIGH)
 *  - Whether strict policy is required (CRITICAL)
 *
 * This is evaluated by the [RiskEngine] before any backend is invoked.
 */
@Serializable
enum class RiskLevel {
    /** Auto-execute. No user interaction required. */
    LOW,
    /** User-configurable: may auto-execute or require confirmation depending on policy. */
    MEDIUM,
    /** Always requires user confirmation unless explicitly overridden in workflow policy. */
    HIGH,
    /** Requires strict signed policy authorization — never auto-executes. */
    CRITICAL;

    fun isAtLeast(other: RiskLevel): Boolean = this.ordinal >= other.ordinal
}

/**
 * Result of evaluating a risk assessment.
 */
@Serializable
data class RiskAssessment(
    val level: RiskLevel,
    val requiresConfirmation: Boolean,
    val requiresSignedPolicy: Boolean,
    val reasons: List<String> = emptyList(),
    val canAutoExecute: Boolean = level == RiskLevel.LOW
)

/**
 * Default risk classifications for core capabilities.
 * Custom plugins or workflow authors may override these via [RiskEngine.overrideRisk].
 */
object DefaultRiskClassification {
    val CAPABILITY_RISK: Map<CapabilityId, RiskLevel> = mapOf(
        CapabilityId.DEVICE_STATE_READ to RiskLevel.LOW,
        CapabilityId.INTENT_LAUNCH to RiskLevel.LOW,
        CapabilityId.SETTINGS_LAUNCH to RiskLevel.LOW,
        CapabilityId.NETWORK_HTTP_REQUEST to RiskLevel.MEDIUM,
        CapabilityId.PACKAGE_READ to RiskLevel.LOW,
        CapabilityId.PACKAGE_FORCE_STOP to RiskLevel.HIGH,
        CapabilityId.PACKAGE_SET_ENABLED to RiskLevel.HIGH,
        CapabilityId.PACKAGE_INSTALL to RiskLevel.HIGH,
        CapabilityId.PACKAGE_UNINSTALL to RiskLevel.HIGH,
        CapabilityId.PACKAGE_CLEAR_DATA to RiskLevel.HIGH,
        CapabilityId.UPDATE_APPS to RiskLevel.MEDIUM,
        CapabilityId.SYSTEM_SETTING_WRITE to RiskLevel.HIGH,
        CapabilityId.FILE_COPY to RiskLevel.HIGH,
        CapabilityId.ACCESSIBILITY_FIND_NODE to RiskLevel.LOW,
        CapabilityId.ACCESSIBILITY_CLICK to RiskLevel.MEDIUM,
        CapabilityId.ACCESSIBILITY_SCROLL to RiskLevel.MEDIUM,
        CapabilityId.ACCESSIBILITY_INPUT_TEXT to RiskLevel.HIGH,
        CapabilityId.ACCESSIBILITY_WAIT_FOR_NODE to RiskLevel.LOW,
        CapabilityId.ACCESSIBILITY_GESTURE to RiskLevel.HIGH,
        CapabilityId.PLUGIN_ACTION to RiskLevel.MEDIUM,
        CapabilityId.PLUGIN_CONDITION_READ to RiskLevel.LOW
    )

    val PRIVILEGE_RISK: Map<PrivilegeLevel, RiskLevel> = mapOf(
        PrivilegeLevel.NONE to RiskLevel.LOW,
        PrivilegeLevel.ADB_SHELL to RiskLevel.HIGH,
        PrivilegeLevel.SHIZUKU to RiskLevel.HIGH,
        PrivilegeLevel.ROOT to RiskLevel.CRITICAL
    )
}

/**
 * The Risk Engine evaluates a capability request before backend resolution.
 *
 * It combines:
 * - Static capability risk (from [DefaultRiskClassification])
 * - Privilege level risk
 * - Workflow-level context (e.g., untrusted source, AI-generated)
 *
 * The result feeds into:
 * - [HumanApprovalNode]: auto-inserted for HIGH+ operations
 * - [ExecutionPolicyEvaluator]: gates backend selection
 * - UI: shows risk badges to the user
 */
class RiskEngine(
    private val overrides: Map<CapabilityId, RiskLevel> = emptyMap()
) {

    /**
     * Evaluates risk for a capability request in a given context.
     *
     * @param capability The capability being requested.
     * @param privilege The privilege level required by the selected backend.
     * @param isAiGenerated True if the request was generated by an AI planner.
     * @param isFromPlugin True if the request originated from a third-party plugin.
     */
    fun assess(
        capability: CapabilityId,
        privilege: PrivilegeLevel = PrivilegeLevel.NONE,
        isAiGenerated: Boolean = false,
        isFromPlugin: Boolean = false
    ): RiskAssessment {
        val capabilityRisk = overrides[capability]
            ?: DefaultRiskClassification.CAPABILITY_RISK[capability]
            ?: RiskLevel.MEDIUM

        val privilegeRisk = DefaultRiskClassification.PRIVILEGE_RISK[privilege] ?: RiskLevel.LOW

        val reasons = mutableListOf<String>()
        var effectiveRisk = maxOf(capabilityRisk, privilegeRisk)

        if (isAiGenerated) {
            // AI-generated actions are escalated by one level as a security guardrail.
            effectiveRisk = escalate(effectiveRisk)
            reasons.add("AI-generated request escalated risk level")
        }

        if (isFromPlugin) {
            effectiveRisk = maxOf(effectiveRisk, RiskLevel.MEDIUM)
            reasons.add("Plugin-originated request assigned at least MEDIUM risk")
        }

        return RiskAssessment(
            level = effectiveRisk,
            requiresConfirmation = effectiveRisk.isAtLeast(RiskLevel.HIGH),
            requiresSignedPolicy = effectiveRisk == RiskLevel.CRITICAL,
            reasons = reasons,
            canAutoExecute = effectiveRisk == RiskLevel.LOW
        )
    }

    /** Elevates [RiskLevel] by one step, capping at CRITICAL. */
    private fun escalate(level: RiskLevel): RiskLevel = when (level) {
        RiskLevel.LOW -> RiskLevel.MEDIUM
        RiskLevel.MEDIUM -> RiskLevel.HIGH
        RiskLevel.HIGH, RiskLevel.CRITICAL -> RiskLevel.CRITICAL
    }

    private fun maxOf(a: RiskLevel, b: RiskLevel): RiskLevel =
        if (a.ordinal >= b.ordinal) a else b
}
