package com.nexaflow.feature.settings

/**
 * Conservative comparison boundary between a GitHub release tag and the
 * installed `versionName` generated by GitVersion.
 *
 * A malformed, unknown, equal, or older remote version is never considered an
 * update. This fail-closed policy prevents a release such as `v3.38.8` from
 * prompting an installation when the app already reports `3.38.8`, or when a
 * development build is already based on that tagged release.
 */
object UpdateVersion {

    /** True only when [remote] is a verifiably newer release than [installed]. */
    fun isStrictlyNewer(remote: String, installed: String): Boolean {
        val remoteVersion = parse(remote) ?: return false
        val installedVersion = parse(installed) ?: return false
        return remoteVersion > installedVersion
    }

    /** Canonical display form used for equality and notification de-duplication. */
    fun canonical(value: String): String? = parse(value)?.canonical

    private fun parse(value: String): ParsedVersion? {
        val raw = value.trim()
        val match = VERSION_PATTERN.matchEntire(raw) ?: return null
        val major = match.groupValues[1].toIntOrNull() ?: return null
        val minor = match.groupValues[2].toIntOrNull() ?: return null
        val patch = match.groupValues[3].toIntOrNull() ?: return null
        val suffix = match.groupValues[4].takeIf { it.isNotBlank() }
        return ParsedVersion(major, minor, patch, suffix)
    }

    private data class ParsedVersion(
        val major: Int,
        val minor: Int,
        val patch: Int,
        val suffix: String?
    ) : Comparable<ParsedVersion> {

        val canonical: String = "$major.$minor.$patch" + suffix?.let { "-$it" }.orEmpty()

        /** Git describes a commit after a tag as `tag-distance-g<hash>`. */
        private val isPostReleaseCommit: Boolean = suffix?.matches(POST_RELEASE_SUFFIX) == true
        private val isStable: Boolean = suffix == null

        override fun compareTo(other: ParsedVersion): Int {
            compareValuesBy(this, other, ParsedVersion::major, ParsedVersion::minor, ParsedVersion::patch)
                .takeIf { it != 0 }
                ?.let { return it }

            // A build made after the current release tag must not be prompted to
            // install the same tagged APK. It is already ahead of that artifact.
            if (isPostReleaseCommit != other.isPostReleaseCommit) {
                return if (isPostReleaseCommit) 1 else -1
            }
            if (isStable != other.isStable) {
                return if (isStable) 1 else -1
            }
            return comparePrerelease(suffix, other.suffix)
        }

        private fun comparePrerelease(left: String?, right: String?): Int {
            if (left == right) return 0
            if (left == null) return 1
            if (right == null) return -1
            val leftParts = left.split('-', '.').filter { it.isNotBlank() }
            val rightParts = right.split('-', '.').filter { it.isNotBlank() }
            val limit = minOf(leftParts.size, rightParts.size)
            repeat(limit) { index ->
                val a = leftParts[index]
                val b = rightParts[index]
                if (a == b) return@repeat
                val aNumber = a.toLongOrNull()
                val bNumber = b.toLongOrNull()
                return when {
                    aNumber != null && bNumber != null -> aNumber.compareTo(bNumber)
                    aNumber != null -> -1
                    bNumber != null -> 1
                    else -> a.compareTo(b, ignoreCase = true)
                }
            }
            return leftParts.size.compareTo(rightParts.size)
        }
    }

    private val VERSION_PATTERN = Regex(
        "^v?(\\d+)\\.(\\d+)\\.(\\d+)(?:-([0-9A-Za-z.-]+))?$"
    )
    private val POST_RELEASE_SUFFIX = Regex("\\d+-g[0-9a-fA-F]+")
}
