package com.nexaflow.domain.canonical

/**
 * T43 — Measured, deterministic performance regression ledger (plan §T43).
 *
 * Structural budgets (T33) cap the *shape* of a workflow. This class adds
 * the missing half: **measured worst cases of the canonical model itself**,
 * evaluated against an explicit, checked-in baseline on every test run —
 * no wall clocks, no randomness, no machine variance.
 *
 * Determinism contract:
 *  - inputs are synthetic worst-case trees generated by a fixed formula
 *    (a maximal-depth spine, a maximal fan-out, an optimizable churn tree),
 *    not random data;
 *  - "measurement" is the exact, platform-independent work counter of the
 *    pure rewrite/measure pipeline (AST validation + optimizer rewrites +
 *    budget measurement) — the same tree always yields the same count on
 *    every JVM, so the comparison cannot flake;
 *  - time-sensitive primitives stay out by construction, mirroring the T27
 *    persistence purity and the T37 fitness patterns.
 *
 * A regression is typed: the baseline, the observed work count and a stable
 * probe name. Improvements do not silently move the baseline; lowering it
 * is an explicit [BASELINES] change reviewed with the numbers in hand.
 */
object CanonicalPerfRegression {

    /** Synthetic worst-case generation limits (mirrors T33 boundaries). */
    const val MAX_DEPTH: Int = CanonicalPerformanceBudget.DEFAULT_MAX_DEPTH
    const val MAX_FAN_OUT: Int = 64

    /** The measured, platform-independent work counter of one pipeline run. */
    data class Measurement(
        /** Exact validation visits over the tree. */
        val validationVisits: Int,
        /** Exact optimizer rewrite actions across all passes. */
        val optimizerRewrites: Int,
        /** Exact budget-measurement visits. */
        val budgetVisits: Int,
        /** Sum of the above: the single compared number. */
        val totalWork: Int,
    ) {
        init {
            require(validationVisits >= 0) { "validationVisits must be >= 0" }
            require(optimizerRewrites >= 0) { "optimizerRewrites must be >= 0" }
            require(budgetVisits >= 0) { "budgetVisits must be >= 0" }
            require(totalWork == validationVisits + optimizerRewrites + budgetVisits) {
                "totalWork must be the exact sum of the counters"
            }
        }
    }

    /** One checked-in reference point: probe name plus its allowed work. */
    data class Baseline(
        val probe: String,
        val allowedWork: Int,
    ) {
        init {
            require(probe.isNotBlank()) { "probe must not be blank" }
            require(allowedWork >= 1) { "allowedWork must be >= 1" }
        }
    }

    /**
     * Why a probe failed; the regression names baseline and observation so
     * the fix is a code review, not a guess.
     */
    sealed class Comparison {
        data object WithinBaseline : Comparison()

        data class Regressed(
            val baseline: Int,
            val observed: Int,
        ) : Comparison()
    }

    /** The full deterministic verdict for one probe. */
    data class ProbeResult(
        val probe: String,
        val measurement: Measurement,
        val comparison: Comparison,
    )

    /**
     * The shipped worst-case probes. `maxDepthSpine` stresses the recursive
     * validator/optimizer at the depth limit; `wideFanOut` stresses the
     * budget measure over many siblings; `optimizerChurn` feeds an already
     * optimizable tree and pins that rewriting converges in bounded passes.
     */
    val PROBES: List<String> = listOf("maxDepthSpine", "wideFanOut", "optimizerChurn")

    /** The checked-in baseline; reviewed with the probe numbers in hand. */
    val BASELINES: List<Baseline> = listOf(
        // maxDepthSpine: 64 validation visits + 0 rewrites + 128 budget visits.
        Baseline("maxDepthSpine", 192),
        // wideFanOut: 65 validation visits + 0 rewrites + 67 budget visits.
        Baseline("wideFanOut", 132),
        // optimizerChurn: 7 validation visits + 4 rewrites + 6 budget visits.
        Baseline("optimizerChurn", 17),
    )

    /**
     * Builds the fixed worst-case tree for [probe]. The formula is part of
     * the contract: changing it changes the meaning of the baseline.
     */
    fun buildProbeTree(probe: String): CanonicalNode = when (probe) {
        "maxDepthSpine" -> spine(MAX_DEPTH)
        "wideFanOut" -> SequenceNode(
            CanonicalNodeId("fan"),
            (1..MAX_FAN_OUT).map {
                SetStateNode(
                    CanonicalNodeId("w$it"),
                    TargetId("core.connectivity.wifi"),
                    BooleanValue(true),
                )
            },
        )
        "optimizerChurn" -> SequenceNode(
            CanonicalNodeId("churn"),
            listOf(
                SetStateNode(CanonicalNodeId("a1"), TargetId("core.connectivity.wifi"), BooleanValue(true)),
                SetStateNode(CanonicalNodeId("a2"), TargetId("core.connectivity.wifi"), BooleanValue(true)),
                SetStateNode(CanonicalNodeId("a3"), TargetId("core.connectivity.wifi"), BooleanValue(true)),
                WaitNode(CanonicalNodeId("t1"), DurationValue(100)),
                WaitNode(CanonicalNodeId("t2"), DurationValue(200)),
                WaitNode(CanonicalNodeId("t3"), DurationValue(300)),
            ),
        )
        else -> throw IllegalArgumentException("unknown probe $probe")
    }

    /**
     * Measures the pure pipeline over the probe tree. The counter is exact:
     * validation visits + optimizer rewrites + budget visits, all
     * deterministic functions of the tree alone.
     */
    fun measure(probe: String): Measurement {
        val tree = buildProbeTree(probe)
        val validationVisits = countTreeVisits(tree)
        // Fails closed: an invalid probe tree throws, it is never measured.
        validateCanonicalAst(tree)
        val optimized = CanonicalConsolidationOptimizer.optimize(tree)
        val budget = CanonicalPerformanceBudget.validateAstOnly(optimized.root)
        val optimizerRewrites = optimized.report.removedNodes
        val budgetVisits = budget.ast.nodeCount + budget.ast.maxDepth + budget.ast.waitCount
        return Measurement(
            validationVisits = validationVisits,
            optimizerRewrites = optimizerRewrites,
            budgetVisits = budgetVisits,
            totalWork = validationVisits + optimizerRewrites + budgetVisits,
        )
    }

    /** Runs one probe against the checked-in baseline. */
    fun runProbe(probe: String, baselines: List<Baseline> = BASELINES): ProbeResult {
        val measurement = measure(probe)
        val baseline = baselines.firstOrNull { it.probe == probe }
            ?: throw IllegalArgumentException("no baseline for probe $probe")
        val comparison = if (measurement.totalWork <= baseline.allowedWork) {
            Comparison.WithinBaseline
        } else {
            Comparison.Regressed(baseline.allowedWork, measurement.totalWork)
        }
        return ProbeResult(probe, measurement, comparison)
    }

    /** The verdict over every probe; a single regression fails the batch. */
    fun runAll(baselines: List<Baseline> = BASELINES): List<ProbeResult> =
        PROBES.map { runProbe(it, baselines) }

    /** Exact structural visit counter over the tree (mirrors the validator). */
    private fun countTreeVisits(node: CanonicalNode): Int = when (node) {
        is SequenceNode -> 1 + node.children.sumOf { countTreeVisits(it) }
        is BranchNode -> 1 + countTreeVisits(node.ifTrue) +
            (node.ifFalse?.let { countTreeVisits(it) } ?: 0)
        else -> 1
    }

    /**
     * Fixed maximal spine: [depth] nested sequences with one leaf each —
     * the worst case for recursive visitors, generated identically always.
     */
    private fun spine(depth: Int): CanonicalNode {
        require(depth in 1..MAX_DEPTH) { "depth must be in 1..$MAX_DEPTH" }
        var node: CanonicalNode = SetStateNode(
            CanonicalNodeId("leaf"),
            TargetId("core.connectivity.wifi"),
            BooleanValue(true),
        )
        for (level in depth downTo 2) {
            node = SequenceNode(CanonicalNodeId("s$level"), listOf(node))
        }
        return node
    }
}
