#!/usr/bin/env python3
"""Translates the remaining English-fallback strings (v3.59.x era) into all
10 non-English locales. Covers: evo_* (Evolver editor), map_* (map picker),
http_* (HTTP request editor), wait_*, rom_setting_trigger_*, end_behavior_*,
misc. English technical literals (NFC, USB, VPN, cols) stay as-is by design.
"""
import re

# key -> {locale-suffix: text}; locales missing from a key keep English.
T = {
 "evo_accent_blue": {"ar":"أزرق","de":"Blau","es":"Azul","fr":"Bleu","hi":"नीला","ja":"ブルー","pt":"Azul","ru":"Синий","tr":"Mavi","zh-rCN":"蓝色"},
 "evo_accent_green": {"ar":"أخضر","de":"Grün","es":"Verde","fr":"Vert","hi":"हरा","ja":"グリーン","pt":"Verde","ru":"Зелёный","tr":"Yeşil","zh-rCN":"绿色"},
 "evo_accent_orange": {"ar":"برتقالي","de":"Orange","es":"Naranja","fr":"Orange","hi":"नारंगी","ja":"オレンジ","pt":"Laranja","ru":"Оранжевый","tr":"Turuncu","zh-rCN":"橙色"},
 "evo_accent_pink": {"ar":"وردي","de":"Pink","es":"Rosa","fr":"Rose","hi":"गुलाबी","ja":"ピンク","pt":"Rosa","ru":"Розовый","tr":"Pembe","zh-rCN":"粉色"},
 "evo_aod_enabled": {"ar":"العرض الدائم","de":"Always-on-Display","es":"Pantalla siempre activa","fr":"Affichage permanent","hi":"हमेशा-चालू डिस्प्ले","ja":"常時表示ディスプレイ","pt":"Tela sempre ativa","ru":"Всегда включённый экран","tr":"Her zaman açık ekran","zh-rCN":"息屏显示"},
 "evo_aod_schedule": {"ar":"جدول","de":"Zeitplan","es":"Horario","fr":"Programme","hi":"शेड्यूल","ja":"スケジュール","pt":"Programação","ru":"Расписание","tr":"Zamanlama","zh-rCN":"时间表"},
 "evo_aod_title": {"ar":"الشاشة المحلية / AOD","de":"Umgebungsanzeige / AOD","es":"Pantalla ambiente / AOD","fr":"Écran ambiant / AOD","hi":"एम्बिएंट / AOD","ja":"アンビエント / AOD","pt":"Tela ambiente / AOD","ru":"Ambient / AOD","tr":"Ortam ekranı / AOD","zh-rCN":"环境显示 / AOD"},
 "evo_batch_hint": {"ar":"اختر إعدادات نظام متعددة وطبقها معًا — يعمل على أي ROM","de":"Wähle mehrere Systemeinstellungen und wende sie gemeinsam an — funktioniert auf jedem ROM","es":"Elige varios ajustes del sistema y aplícalos juntos — funciona en cualquier ROM","fr":"Choisissez plusieurs réglages système et appliquez-les ensemble — fonctionne sur toute ROM","hi":"कई सिस्टम सेटिंग चुनें और एक साथ लागू करें — किसी भी ROM पर काम करता है","ja":"複数のシステム設定を選んで一緒に適用 — どの ROM でも動作","pt":"Escolha várias configurações do sistema e aplique-as juntas — funciona em qualquer ROM","ru":"Выберите несколько системных настроек и примените вместе — работает на любой ROM","tr":"Birden çok sistem ayarı seçin ve birlikte uygulayın — her ROM'da çalışır","zh-rCN":"选择多个系统设置并一起应用 — 适用于任何 ROM"},
 "evo_batch_json": {"ar":"JSON للدفعة","de":"Batch-JSON","es":"JSON del lote","fr":"JSON du lot","hi":"बैच JSON","ja":"バッチ JSON","pt":"JSON do lote","ru":"Пакетный JSON","tr":"Toplu JSON","zh-rCN":"批量 JSON"},
 "evo_batch_key_battery": {"ar":"البطارية","de":"Akku","es":"Batería","fr":"Batterie","hi":"बैटरी","ja":"バッテリー","pt":"Bateria","ru":"Батарея","tr":"Pil","zh-rCN":"电池"},
 "evo_batch_key_lockscreen": {"ar":"شاشة القفل","de":"Sperrbildschirm","es":"Pantalla de bloqueo","fr":"Écran de verrouillage","hi":"लॉक स्क्रीन","ja":"ロック画面","pt":"Tela de bloqueio","ru":"Экран блокировки","tr":"Kilit ekranı","zh-rCN":"锁屏"},
 "evo_batch_key_qs": {"ar":"بلاطات الإعدادات السريعة","de":"QS-Kacheln","es":"Tarjetas de ajustes rápidos","fr":"Tuiles de réglages rapides","hi":"क्विक सेटिंग्स टाइल","ja":"クイック設定タイル","pt":"Blocos de configurações rápidas","ru":"Плитки быстрых настроек","tr":"Hızlı ayar kutucukları","zh-rCN":"快捷设置图块"},
 "evo_batch_title": {"ar":"دفعة — إعدادات متعددة في وقت واحد","de":"Batch — mehrere Einstellungen auf einmal","es":"Lote — varios ajustes a la vez","fr":"Lot — plusieurs réglages à la fois","hi":"बैच — एक साथ कई सेटिंग","ja":"バッチ — 複数設定を一度に","pt":"Lote — várias configurações de uma vez","ru":"Пакет — несколько настроек сразу","tr":"Toplu — aynı anda birden çok ayar","zh-rCN":"批量 — 一次多个设置"},
 "evo_battery_circle": {"ar":"دائرة","de":"Kreis","es":"Círculo","fr":"Cercle","hi":"वृत्त","ja":"円形","pt":"Círculo","ru":"Круг","tr":"Daire","zh-rCN":"圆形"},
 "evo_battery_hidden": {"ar":"مخفية","de":"Ausgeblendet","es":"Oculta","fr":"Masquée","hi":"छिपी हुई","ja":"非表示","pt":"Oculta","ru":"Скрыта","tr":"Gizli","zh-rCN":"隐藏"},
 "evo_battery_icon": {"ar":"أيقونة","de":"Symbol","es":"Icono","fr":"Icône","hi":"आइकन","ja":"アイコン","pt":"Ícone","ru":"Значок","tr":"Simge","zh-rCN":"图标"},
 "evo_battery_text": {"ar":"نص","de":"Text","es":"Texto","fr":"Texte","hi":"टेक्स्ट","ja":"テキスト","pt":"Texto","ru":"Текст","tr":"Metin","zh-rCN":"文本"},
 "evo_clock_bold": {"ar":"عريض","de":"Fett","es":"Negrita","fr":"Gras","hi":"बोल्ड","ja":"太字","pt":"Negrito","ru":"Жирный","tr":"Kalın","zh-rCN":"粗体"},
 "evo_clock_default": {"ar":"افتراضي","de":"Standard","es":"Predeterminado","fr":"Par défaut","hi":"डिफ़ॉल्ट","ja":"デフォルト","pt":"Padrão","ru":"По умолчанию","tr":"Varsayılan","zh-rCN":"默认"},
 "evo_clock_minimal": {"ar":"مبسّط","de":"Minimal","es":"Minimalista","fr":"Minimaliste","hi":"न्यूनतम","ja":"ミニマル","pt":"Minimalista","ru":"Минималистичный","tr":"Minimal","zh-rCN":"极简"},
 "evo_clock_weather": {"ar":"الطقس","de":"Wetter","es":"Clima","fr":"Météo","hi":"मौसम","ja":"天気","pt":"Clima","ru":"Погода","tr":"Hava durumu","zh-rCN":"天气"},
 "evo_custom_hint": {"ar":"اختر أي إعداد نظام من مفاتيح الجهاز الحية. يعمل على أي ROM.","de":"Wähle eine beliebige Systemeinstellung aus den Live-Schlüsseln des Geräts. Funktioniert auf jedem ROM.","es":"Elige cualquier ajuste del sistema de las claves en vivo del dispositivo. Funciona en cualquier ROM.","fr":"Choisissez n\u2019importe quel réglage système parmi les clés en direct de l\u2019appareil. Fonctionne sur toute ROM.","hi":"डिवाइस की लाइव कुंजियों में से कोई भी सिस्टम सेटिंग चुनें। किसी भी ROM पर काम करता है।","ja":"デバイスのライブキーから任意のシステム設定を選択。どの ROM でも動作します。","pt":"Escolha qualquer configuração do sistema nas chaves ao vivo do dispositivo. Funciona em qualquer ROM.","ru":"Выберите любую системную настройку из живых ключей устройства. Работает на любой ROM.","tr":"Cihazın canlı anahtarlarından herhangi bir sistem ayarını seçin. Her ROM'da çalışır.","zh-rCN":"从设备的实时键中选择任意系统设置。适用于任何 ROM。"},
 "evo_custom_key_label": {"ar":"مفتاح الإعداد (مثال: sysui_qs_tiles)","de":"Einstellungsschlüssel (z. B. sysui_qs_tiles)","es":"Clave de ajuste (p. ej. sysui_qs_tiles)","fr":"Clé de réglage (ex. sysui_qs_tiles)","hi":"सेटिंग कुंजी (जैसे sysui_qs_tiles)","ja":"設定キー（例: sysui_qs_tiles）","pt":"Chave de configuração (ex.: sysui_qs_tiles)","ru":"Ключ настройки (напр. sysui_qs_tiles)","tr":"Ayar anahtarı (ör. sysui_qs_tiles)","zh-rCN":"设置键（例如 sysui_qs_tiles）"},
 "evo_custom_pick": {"ar":"اختر إعدادًا…","de":"Einstellung wählen…","es":"Elegir ajuste…","fr":"Choisir un réglage…","hi":"सेटिंग चुनें…","ja":"設定を選択…","pt":"Escolher configuração…","ru":"Выбрать настройку…","tr":"Ayar seç…","zh-rCN":"选择设置…"},
 "evo_custom_title": {"ar":"إعداد نظام مخصص","de":"Benutzerdefinierte Systemeinstellung","es":"Ajuste del sistema personalizado","fr":"Réglage système personnalisé","hi":"कस्टम सिस्टम सेटिंग","ja":"カスタムシステム設定","pt":"Configuração personalizada do sistema","ru":"Пользовательская системная настройка","tr":"Özel sistem ayarı","zh-rCN":"自定义系统设置"},
 "evo_custom_value_custom": {"ar":"قيمة مخصصة","de":"Benutzerdefinierter Wert","es":"Valor personalizado","fr":"Valeur personnalisée","hi":"कस्टम मान","ja":"カスタム値","pt":"Valor personalizado","ru":"Своё значение","tr":"Özel değer","zh-rCN":"自定义值"},
 "evo_custom_value_label": {"ar":"القيمة","de":"Wert","es":"Valor","fr":"Valeur","hi":"मान","ja":"値","pt":"Valor","ru":"Значение","tr":"Değer","zh-rCN":"值"},
 "evo_custom_value_placeholder": {"ar":"أو اكتب أي قيمة…","de":"oder beliebigen Wert eingeben…","es":"o escribe cualquier valor…","fr":"ou saisissez une valeur…","hi":"या कोई भी मान लिखें…","ja":"または任意の値を入力…","pt":"ou digite qualquer valor…","ru":"или введите любое значение…","tr":"veya herhangi bir değer yazın…","zh-rCN":"或输入任意值…"},
 "evo_lockscreen_clock_style": {"ar":"نمط الساعة","de":"Uhrenstil","es":"Estilo del reloj","fr":"Style d\u2019horloge","hi":"घड़ी शैली","ja":"時計のスタイル","pt":"Estilo do relógio","ru":"Стиль часов","tr":"Saat stili","zh-rCN":"时钟样式"},
 "evo_lockscreen_hint": {"ar":"الساعة والاختصارات والطقس وبصمة الشاشة","de":"Uhr, Verknüpfungen, Wetter, UDFPS","es":"Reloj, accesos directos, clima, UDFPS","fr":"Horloge, raccourcis, météo, UDFPS","hi":"घड़ी, शॉर्टकट, मौसम, UDFPS","ja":"時計・ショートカット・天気・UDFPS","pt":"Relógio, atalhos, clima, UDFPS","ru":"Часы, ярлыки, погода, UDFPS","tr":"Saat, kısayollar, hava durumu, UDFPS","zh-rCN":"时钟、快捷方式、天气、屏下指纹"},
 "evo_lockscreen_media_art": {"ar":"صورة الوسائط","de":"Medienbild","es":"Portada multimedia","fr":"Pochette média","hi":"मीडिया कला","ja":"メディアアート","pt":"Arte de mídia","ru":"Обложка медиа","tr":"Medya görseli","zh-rCN":"媒体封面"},
 "evo_lockscreen_shortcuts": {"ar":"إظهار الاختصارات","de":"Verknüpfungen zeigen","es":"Mostrar accesos directos","fr":"Afficher les raccourcis","hi":"शॉर्टकट दिखाएँ","ja":"ショートカットを表示","pt":"Mostrar atalhos","ru":"Показать ярлыки","tr":"Kısayolları göster","zh-rCN":"显示快捷方式"},
 "evo_lockscreen_title": {"ar":"شاشة القفل","de":"Sperrbildschirm","es":"Pantalla de bloqueo","fr":"Écran de verrouillage","hi":"लॉक स्क्रीन","ja":"ロック画面","pt":"Tela de bloqueio","ru":"Экран блокировки","tr":"Kilit ekranı","zh-rCN":"锁屏"},
 "evo_lockscreen_weather": {"ar":"إظهار الطقس","de":"Wetter zeigen","es":"Mostrar clima","fr":"Afficher la météo","hi":"मौसम दिखाएँ","ja":"天気を表示","pt":"Mostrar clima","ru":"Показать погоду","tr":"Hava durumunu göster","zh-rCN":"显示天气"},
 "evo_nav_2button": {"ar":"زران","de":"2-Tasten","es":"2 botones","fr":"2 boutons","hi":"2 बटन","ja":"2ボタン","pt":"2 botões","ru":"2 кнопки","tr":"2 düğme","zh-rCN":"双按钮"},
 "evo_nav_3button": {"ar":"ثلاثة أزرار","de":"3-Tasten","es":"3 botones","fr":"3 boutons","hi":"3 बटन","ja":"3ボタン","pt":"3 botões","ru":"3 кнопки","tr":"3 düğme","zh-rCN":"三按钮"},
 "evo_nav_back_default": {"ar":"افتراضي","de":"Standard","es":"Predeterminada","fr":"Par défaut","hi":"डिफ़ॉल्ट","ja":"デフォルト","pt":"Padrão","ru":"По умолчанию","tr":"Varsayılan","zh-rCN":"默认"},
 "evo_nav_back_full": {"ar":"كامل","de":"Voll","es":"Completa","fr":"Complète","hi":"पूर्ण","ja":"全幅","pt":"Total","ru":"Полная","tr":"Tam","zh-rCN":"全高"},
 "evo_nav_back_height": {"ar":"ارتفاع إيماءة الرجوع","de":"Höhe der Rückgeste","es":"Altura del gesto atrás","fr":"Hauteur du geste retour","hi":"बैक जेस्चर ऊँचाई","ja":"戻るジェスチャーの高さ","pt":"Altura do gesto de voltar","ru":"Высота жеста «назад»","tr":"Geri hareketi yüksekliği","zh-rCN":"返回手势高度"},
 "evo_nav_back_high": {"ar":"عالٍ","de":"Hoch","es":"Alta","fr":"Haute","hi":"उच्च","ja":"高","pt":"Alta","ru":"Высокая","tr":"Yüksek","zh-rCN":"高"},
 "evo_nav_back_low": {"ar":"منخفض","de":"Niedrig","es":"Baja","fr":"Basse","hi":"निम्न","ja":"低","pt":"Baixa","ru":"Низкая","tr":"Düşük","zh-rCN":"低"},
 "evo_nav_back_medium": {"ar":"متوسط","de":"Mittel","es":"Media","fr":"Moyenne","hi":"मध्यम","ja":"中","pt":"Média","ru":"Средняя","tr":"Orta","zh-rCN":"中"},
 "evo_nav_gesture": {"ar":"إيماءات","de":"Geste","es":"Gestos","fr":"Gestes","hi":"जेस्चर","ja":"ジェスチャー","pt":"Gestos","ru":"Жесты","tr":"Hareket","zh-rCN":"手势"},
 "evo_nav_mode": {"ar":"النمط","de":"Modus","es":"Modo","fr":"Mode","hi":"मोड","ja":"モード","pt":"Modo","ru":"Режим","tr":"Mod","zh-rCN":"模式"},
 "evo_nav_title": {"ar":"التنقل","de":"Navigation","es":"Navegación","fr":"Navigation","hi":"नेविगेशन","ja":"ナビゲーション","pt":"Navegação","ru":"Навигация","tr":"Gezinme","zh-rCN":"导航"},
 "evo_notif_heads_up": {"ar":"تنبيه سريع","de":"Heads-up","es":"Aviso emergente","fr":"Notification flash","hi":"हेड्स-अप","ja":"ヘッドアップ","pt":"Notificação instantânea","ru":"Всплывающие","tr":"Hızlı bildirim","zh-rCN":"悬浮通知"},
 "evo_notif_less_boring": {"ar":"إشعارات أقل إزعاجًا","de":"Weniger aufdringlich","es":"Notificaciones menos intrusivas","fr":"Notifications moins intrusives","hi":"कम खलल डालने वाली सूचनाएँ","ja":"控えめな通知","pt":"Notificações menos intrusivas","ru":"Менее навязчивые уведомления","tr":"Daha az rahatsız edici bildirim","zh-rCN":"降低打扰"},
 "evo_notif_timeout": {"ar":"المهلة","de":"Timeout","es":"Tiempo de espera","fr":"Délai","hi":"टाइमआउट","ja":"タイムアウト","pt":"Tempo limite","ru":"Тайм-аут","tr":"Zaman aşımı","zh-rCN":"超时"},
 "evo_notif_title": {"ar":"التنبيهات السريعة والإشعارات","de":"Heads-up &amp; Benachrichtigungen","es":"Avisos emergentes y notificaciones","fr":"Notifications flash et notifications","hi":"हेड्स-अप और सूचनाएँ","ja":"ヘッドアップと通知","pt":"Avisos instantâneos e notificações","ru":"Всплывающие и уведомления","tr":"Hızlı bildirim ve bildirimler","zh-rCN":"悬浮通知与通知"},
 "evo_off": {"ar":"إيقاف","de":"Aus","es":"Apagado","fr":"Désactivé","hi":"बंद","ja":"オフ","pt":"Desligado","ru":"Выкл.","tr":"Kapalı","zh-rCN":"关"},
 "evo_pos_center": {"ar":"الوسط","de":"Mitte","es":"Centro","fr":"Centre","hi":"केंद्र","ja":"中央","pt":"Centro","ru":"По центру","tr":"Orta","zh-rCN":"居中"},
 "evo_pos_left": {"ar":"اليسار","de":"Links","es":"Izquierda","fr":"Gauche","hi":"बाएँ","ja":"左","pt":"Esquerda","ru":"Слева","tr":"Sol","zh-rCN":"左侧"},
 "evo_pos_right": {"ar":"اليمين","de":"Rechts","es":"Derecha","fr":"Droite","hi":"दाएँ","ja":"右","pt":"Direita","ru":"Справа","tr":"Sağ","zh-rCN":"右侧"},
 "evo_qs_brightness_slider": {"ar":"إظهار شريط السطوع","de":"Helligkeitsregler zeigen","es":"Mostrar control de brillo","fr":"Afficher le curseur de luminosité","hi":"ब्राइटनेस स्लाइडर दिखाएँ","ja":"明るさスライダーを表示","pt":"Mostrar controle de brilho","ru":"Показать ползунок яркости","tr":"Parlaklık kaydırıcısını göster","zh-rCN":"显示亮度滑块"},
 "evo_qs_cols_suffix": {"ar":" أعمدة","de":" Spalten","es":" columnas","fr":" colonnes","hi":" कॉलम","ja":"列","pt":" colunas","ru":" столб.","tr":" sütun","zh-rCN":" 列"},
 "evo_qs_columns": {"ar":"الأعمدة","de":"Spalten","es":"Columnas","fr":"Colonnes","hi":"कॉलम","ja":"列数","pt":"Colunas","ru":"Столбцы","tr":"Sütunlar","zh-rCN":"列数"},
 "evo_qs_footer_field": {"ar":"نص التذييل (اختياري)","de":"Fußzeilentext (optional)","es":"Texto de pie (opcional)","fr":"Texte de pied (facultatif)","hi":"फुटर टेक्स्ट (वैकल्पिक)","ja":"フッターテキスト（任意）","pt":"Texto do rodapé (opcional)","ru":"Текст футера (необязательно)","tr":"Alt bilgi metni (isteğe bağlı)","zh-rCN":"页脚文本（可选）"},
 "evo_qs_footer_placeholder": {"ar":"تذييل مخصص للإعدادات السريعة…","de":"Eigene QS-Fußzeile…","es":"Pie personalizado de ajustes rápidos…","fr":"Pied personnalisé des réglages rapides…","hi":"कस्टम QS फुटर…","ja":"カスタム QS フッター…","pt":"Rodapé personalizado das configurações rápidas…","ru":"Свой футер быстрых настроек…","tr":"Özel hızlı ayar alt bilgisi…","zh-rCN":"自定义快捷设置页脚…"},
 "evo_qs_footer_toggle": {"ar":"إظهار نص التذييل","de":"Fußzeilentext zeigen","es":"Mostrar texto de pie","fr":"Afficher le texte de pied","hi":"फुटर टेक्स्ट दिखाएँ","ja":"フッターテキストを表示","pt":"Mostrar texto do rodapé","ru":"Показать текст футера","tr":"Alt bilgi metnini göster","zh-rCN":"显示页脚文本"},
 "evo_qs_hint": {"ar":"اضغط لاختيار البلاطات — يعمل على أي ROM","de":"Zum Auswählen der Kacheln tippen — funktioniert auf jedem ROM","es":"Toca para elegir tarjetas — funciona en cualquier ROM","fr":"Touchez pour choisir des tuiles — fonctionne sur toute ROM","hi":"टाइल चुनने के लिए टैप करें — किसी भी ROM पर काम करता है","ja":"タップしてタイルを選択 — どの ROM でも動作","pt":"Toque para escolher blocos — funciona em qualquer ROM","ru":"Нажмите, чтобы выбрать плитки — работает на любой ROM","tr":"Kutucukları seçmek için dokunun — her ROM'da çalışır","zh-rCN":"点按以选择图块 — 适用于任何 ROM"},
 "evo_qs_title": {"ar":"بلاطات الإعدادات السريعة","de":"Schnelleinstellungen","es":"Tarjetas de ajustes rápidos","fr":"Tuiles de réglages rapides","hi":"क्विक सेटिंग्स टाइल","ja":"クイック設定タイル","pt":"Configurações rápidas","ru":"Быстрые настройки","tr":"Hızlı Ayarlar","zh-rCN":"快捷设置图块"},
 "evo_schedule_night": {"ar":"ليلي","de":"Nacht","es":"Noche","fr":"Nuit","hi":"रात","ja":"夜","pt":"Noite","ru":"Ночь","tr":"Gece","zh-rCN":"夜间"},
 "evo_schedule_off": {"ar":"إيقاف","de":"Aus","es":"Apagado","fr":"Désactivé","hi":"बंद","ja":"オフ","pt":"Desligado","ru":"Выкл.","tr":"Kapalı","zh-rCN":"关"},
 "evo_status_battery_percent": {"ar":"إظهار نسبة البطارية","de":"AkkuProzent zeigen","es":"Mostrar porcentaje de batería","fr":"Afficher le pourcentage de batterie","hi":"बैटरी प्रतिशत दिखाएँ","ja":"バッテリー残量を表示","pt":"Mostrar porcentagem da bateria","ru":"Показывать процент батареи","tr":"Pil yüzdesini göster","zh-rCN":"显示电池百分比"},
 "evo_status_battery_style": {"ar":"نمط البطارية","de":"Akkustil","es":"Estilo de batería","fr":"Style de batterie","hi":"बैटरी शैली","ja":"バッテリーのスタイル","pt":"Estilo da bateria","ru":"Стиль батареи","tr":"Pil stili","zh-rCN":"电池样式"},
 "evo_status_clock_position": {"ar":"موضع الساعة","de":"Uhrenposition","es":"Posición del reloj","fr":"Position de l\u2019horloge","hi":"घड़ी की स्थिति","ja":"時計の位置","pt":"Posição do relógio","ru":"Положение часов","tr":"Saat konumu","zh-rCN":"时钟位置"},
 "evo_status_clock_seconds": {"ar":"إظهار الثواني في الساعة","de":"Sekunden in der Uhr zeigen","es":"Mostrar segundos en el reloj","fr":"Afficher les secondes de l\u2019horloge","hi":"घड़ी में सेकंड दिखाएँ","ja":"時計に秒を表示","pt":"Mostrar segundos no relógio","ru":"Показывать секунды в часах","tr":"Saatte saniyeleri göster","zh-rCN":"时钟显示秒"},
 "evo_status_hint": {"ar":"الساعة والبطارية والأيقونات — يعمل على أي ROM","de":"Uhr, Akku, Symbole — funktioniert auf jedem ROM","es":"Reloj, batería, iconos — funciona en cualquier ROM","fr":"Horloge, batterie, icônes — fonctionne sur toute ROM","hi":"घड़ी, बैटरी, आइकन — किसी भी ROM पर काम करता है","ja":"時計・バッテリー・アイコン — どの ROM でも動作","pt":"Relógio, bateria, ícones — funciona em qualquer ROM","ru":"Часы, батарея, значки — работает на любой ROM","tr":"Saat, pil, simgeler — her ROM'da çalışır","zh-rCN":"时钟、电池、图标 — 适用于任何 ROM"},
 "evo_status_title": {"ar":"شريط الحالة","de":"Statusleiste","es":"Barra de estado","fr":"Barre d\u2019état","hi":"स्टेटस बार","ja":"ステータスバー","pt":"Barra de status","ru":"Строка состояния","tr":"Durum çubuğu","zh-rCN":"状态栏"},
 "evo_theme_accent": {"ar":"لون التمييز","de":"Akzentfarbe","es":"Color de acento","fr":"Couleur d\u2019accent","hi":"एक्सेंट रंग","ja":"アクセントカラー","pt":"Cor de destaque","ru":"Акцентный цвет","tr":"Vurgu rengi","zh-rCN":"强调色"},
 "evo_theme_hint": {"ar":"مونيه ولون التمييز والأيقونات والخطوط","de":"Monet, Akzentfarbe, Symbole, Schriftarten","es":"Monet, acento, iconos, fuentes","fr":"Monet, accent, icônes, polices","hi":"मोनेट, एक्सेंट, आइकन, फ़ॉन्ट","ja":"Monet、アクセント、アイコン、フォント","pt":"Monet, destaque, ícones, fontes","ru":"Monet, акцент, значки, шрифты","tr":"Monet, vurgu, simgeler, yazı tipleri","zh-rCN":"Monet、强调色、图标、字体"},
 "evo_theme_monet": {"ar":"سمات مونيه","de":"Monet-Farbgebung","es":"Temas Monet","fr":"Thèmes Monet","hi":"मोनेट थीमिंग","ja":"Monet テーマ","pt":"Temas Monet","ru":"Темы Monet","tr":"Monet temalı","zh-rCN":"Monet 动态取色"},
 "evo_theme_themed_icons": {"ar":"أيقونات ملونة","de":"Themierte Symbole","es":"Iconos temáticos","fr":"Icônes thématisées","hi":"थीम्ड आइकन","ja":"テーマアイコン","pt":"Ícones temáticos","ru":"Тематические значки","tr":"Temalı simgeler","zh-rCN":"主题图标"},
 "evo_theme_title": {"ar":"السمات","de":"Design","es":"Temas","fr":"Thèmes","hi":"थीमिंग","ja":"テーマ","pt":"Temas","ru":"Оформление","tr":"Tema","zh-rCN":"主题"},
 "http_advanced_label": {"ar":"المهلة وإعادة المحاولة","de":"Timeout und Wiederholungen","es":"Tiempo de espera y reintentos","fr":"Délai et tentatives","hi":"टाइमआउट और पुनः प्रयास","ja":"タイムアウトと再試行","pt":"Tempo limite e repetições","ru":"Тайм-аут и повторы","tr":"Zaman aşımı ve yeniden deneme","zh-rCN":"超时与重试"},
 "http_output_path": {"ar":"تخزين الاستجابة في مسار السياق (اختياري)","de":"Antwort im Kontextpfad speichern (optional)","es":"Guardar respuesta en ruta de contexto (opcional)","fr":"Stocker la réponse à un chemin de contexte (facultatif)","hi":"प्रतिक्रिया को संदर्भ पथ पर सहेजें (वैकल्पिक)","ja":"レスポンスをコンテキストパスに保存（任意）","pt":"Armazenar resposta no caminho de contexto (opcional)","ru":"Сохранить ответ по пути контекста (необязательно)","tr":"Yanıtı bağlam yoluna kaydet (isteğe bağlı)","zh-rCN":"将响应存储到上下文路径（可选）"},
 "http_output_path_hint": {"ar":"يمكن للإجراءات اللاحقة قراءته عبر محددات %CTX.","de":"Spätere Aktionen können ihn über %CTX-Selektoren lesen.","es":"Las acciones posteriores pueden leerlo mediante selectores %CTX.","fr":"Les actions suivantes peuvent le lire via les sélecteurs %CTX.","hi":"बाद की क्रियाएँ इसे %CTX चयनकर्ताओं से पढ़ सकती हैं।","ja":"後続のアクションは %CTX セレクターで読み取れます。","pt":"Ações posteriores podem lê-lo via seletores %CTX.","ru":"Последующие действия могут читать его через селекторы %CTX.","tr":"Sonraki eylemler %CTX seçicileriyle okuyabilir.","zh-rCN":"后续操作可通过 %CTX 选择器读取。"},
 "http_retries_label": {"ar":"محاولات إعادة المحاولة عند الفشل","de":"Wiederholungsversuche bei Fehlschlag","es":"Reintentos en caso de fallo","fr":"Nouvelles tentatives en cas d\u2019échec","hi":"विफलता पर पुनः प्रयास","ja":"失敗時の再試行回数","pt":"Tentativas de repetição em falha","ru":"Повторные попытки при сбое","tr":"Başarısızlıkta yeniden deneme sayısı","zh-rCN":"失败时重试次数"},
 "http_timeout_hint": {"ar":"مدة انتظار الخادم قبل الاستسلام.","de":"Wie lange auf den Server gewartet wird, bevor abgebrochen wird.","es":"Cuánto esperar al servidor antes de rendirse.","fr":"Combien de temps attendre le serveur avant d\u2019abandonner.","hi":"हारने से पहले सर्वर की प्रतीक्षा कितनी देर।","ja":"諦めるまでサーバーを待つ時間。","pt":"Quanto esperar pelo servidor antes de desistir.","ru":"Сколько ждать сервер, прежде чем сдаться.","tr":"Vazgeçmeden önce sunucu ne kadar beklenir.","zh-rCN":"放弃前等待服务器的时长。"},
 "map_copied_feedback": {"ar":"تم نسخ الإحداثيات إلى الحافظة","de":"Koordinaten in die Zwischenablage kopiert","es":"Coordenadas copiadas al portapapeles","fr":"Coordonnées copiées dans le presse-papiers","hi":"निर्देशांक क्लिपबोर्ड पर कॉपी हुए","ja":"座標をクリップボードにコピーしました","pt":"Coordenadas copiadas para a área de transferência","ru":"Координаты скопированы в буфер обмена","tr":"Koordinatlar panoya kopyalandı","zh-rCN":"坐标已复制到剪贴板"},
 "map_copy_coordinates": {"ar":"نسخ الإحداثيات","de":"Koordinaten kopieren","es":"Copiar coordenadas","fr":"Copier les coordonnées","hi":"निर्देशांक कॉपी करें","ja":"座標をコピー","pt":"Copiar coordenadas","ru":"Копировать координаты","tr":"Koordinatları kopyala","zh-rCN":"复制坐标"},
 "map_error_coordinates": {"ar":"أدخل خط عرض صالحًا (-90 إلى 90) وخط طولًا صالحًا (-180 إلى 180).","de":"Gültigen Breitengrad (-90 bis 90) und Längengrad (-180 bis 180) eingeben.","es":"Introduce una latitud válida (-90 a 90) y longitud (-180 a 180).","fr":"Saisissez une latitude valide (-90 à 90) et une longitude valide (-180 à 180).","hi":"मान्य अक्षांश (-90 से 90) और देशांतर (-180 से 180) दर्ज करें।","ja":"有効な緯度（-90〜90）と経度（-180〜180）を入力してください。","pt":"Insira uma latitude válida (-90 a 90) e longitude (-180 a 180).","ru":"Введите допустимую широту (-90…90) и долготу (-180…180).","tr":"Geçerli bir enlem (-90 ile 90) ve boylam (-180 ile 180) girin.","zh-rCN":"请输入有效的纬度（-90 到 90）和经度（-180 到 180）。"},
 "map_error_radius": {"ar":"يجب أن يكون نصف القطر بين 50 و 2000 متر.","de":"Radius muss zwischen 50 und 2000 Metern liegen.","es":"El radio debe estar entre 50 y 2000 metros.","fr":"Le rayon doit être compris entre 50 et 2000 mètres.","hi":"त्रिज्या 50 और 2000 मीटर के बीच होनी चाहिए।","ja":"半径は 50〜2000 メートルの間で指定してください。","pt":"O raio deve estar entre 50 e 2000 metros.","ru":"Радиус должен быть от 50 до 2000 метров.","tr":"Yarıçap 50 ile 2000 metre arasında olmalıdır.","zh-rCN":"半径必须在 50 到 2000 米之间。"},
 "map_latitude": {"ar":"خط العرض","de":"Breitengrad","es":"Latitud","fr":"Latitude","hi":"अक्षांश","ja":"緯度","pt":"Latitude","ru":"Широта","tr":"Enlem","zh-rCN":"纬度"},
 "map_longitude": {"ar":"خط الطول","de":"Längengrad","es":"Longitud","fr":"Longitude","hi":"देशांतर","ja":"経度","pt":"Longitude","ru":"Долгота","tr":"Boylam","zh-rCN":"经度"},
 "map_no_maps_app": {"ar":"لا يوجد تطبيق خرائط متوافق مثبت. أدخل الإحداثيات يدويًا.","de":"Keine kompatible Karten-App installiert. Koordinaten manuell eingeben.","es":"No hay una app de mapas compatible instalada. Introduce las coordenadas manualmente.","fr":"Aucune application de cartes compatible installée. Saisissez les coordonnées manuellement.","hi":"कोई संगत मैप्स ऐप स्थापित नहीं है। निर्देशांक मैन्युअल रूप से दर्ज करें।","ja":"互換性のある地図アプリがインストールされていません。座標を手動で入力してください。","pt":"Nenhum app de mapas compatível instalado. Insira as coordenadas manualmente.","ru":"Совместимое картографическое приложение не установлено. Введите координаты вручную.","tr":"Uyumlu bir harita uygulaması yüklü değil. Koordinatları elle girin.","zh-rCN":"未安装兼容的地图应用。请手动输入坐标。"},
 "map_open_maps_app": {"ar":"فتح تطبيق الخرائط","de":"Karten-App öffnen","es":"Abrir app de mapas","fr":"Ouvrir l\u2019application de cartes","hi":"मैप्स ऐप खोलें","ja":"地図アプリを開く","pt":"Abrir app de mapas","ru":"Открыть картографическое приложение","tr":"Harita uygulamasını aç","zh-rCN":"打开地图应用"},
 "map_paste_coordinates": {"ar":"لصق الإحداثيات","de":"Koordinaten einfügen","es":"Pegar coordenadas","fr":"Coller les coordonnées","hi":"निर्देशांक पेस्ट करें","ja":"座標を貼り付け","pt":"Colar coordenadas","ru":"Вставить координаты","tr":"Koordinatları yapıştır","zh-rCN":"粘贴坐标"},
 "map_paste_failed": {"ar":"لا توجد إحداثيات في الحافظة. انسخ مكانًا أو زوج lat,lng أولًا.","de":"Keine Koordinaten in der Zwischenablage. Kopiere zuerst einen Ort oder ein lat,lng-Paar.","es":"No hay coordenadas en el portapapeles. Copia antes un lugar o un par lat,lng.","fr":"Aucune coordonnée dans le presse-papiers. Copiez d\u2019abord un lieu ou une paire lat,lng.","hi":"क्लिपबोर्ड में कोई निर्देशांक नहीं। पहले कोई जगह या lat,lng जोड़ी कॉपी करें।","ja":"クリップボードに座標がありません。先に場所または lat,lng の組をコピーしてください。","pt":"Nenhuma coordenada na área de transferência. Copie antes um lugar ou um par lat,lng.","ru":"В буфере обмена нет координат. Сначала скопируйте место или пару lat,lng.","tr":"Panoda koordinat yok. Önce bir yer veya lat,lng çifti kopyalayın.","zh-rCN":"剪贴板中没有坐标。请先复制地点或 lat,lng 坐标对。"},
 "map_picker_hint": {"ar":"افتح تطبيق الخرائط المثبت للبحث أو اختيار مكان، ثم انسخ إحداثياته والصقها هنا.","de":"Öffne deine installierte Karten-App, um einen Ort zu suchen oder auszuwählen, kopiere seine Koordinaten und füge sie hier ein.","es":"Abre tu app de mapas instalada para buscar o seleccionar un lugar, luego copia sus coordenadas y pégalas aquí.","fr":"Ouvrez votre application de cartes installée pour chercher ou choisir un lieu, puis copiez ses coordonnées et collez-les ici.","hi":"खोजने या कोई जगह चुनने के लिए अपना स्थापित मैप्स ऐप खोलें, फिर उसके निर्देशांक कॉपी करके यहाँ पेस्ट करें।","ja":"インストール済みの地図アプリを開いて場所を検索・選択し、その座標をコピーしてここに貼り付けてください。","pt":"Abra seu app de mapas instalado para buscar ou selecionar um lugar, depois copie suas coordenadas e cole aqui.","ru":"Откройте установленное картографическое приложение, найдите или выберите место, скопируйте его координаты и вставьте сюда.","tr":"Yer aramak veya seçmek için yüklü harita uygulamanızı açın, koordinatlarını kopyalayıp buraya yapıştırın.","zh-rCN":"打开已安装的地图应用搜索或选择地点，然后复制其坐标并粘贴到此处。"},
 "map_picker_title": {"ar":"اختيار الموقع","de":"Standort wählen","es":"Elegir ubicación","fr":"Choisir un lieu","hi":"स्थान चुनें","ja":"場所を選択","pt":"Escolher local","ru":"Выбрать место","tr":"Konum seç","zh-rCN":"选择位置"},
 "map_radius_meters": {"ar":"نصف القطر (بالأمتار)","de":"Radius (Meter)","es":"Radio (metros)","fr":"Rayon (mètres)","hi":"त्रिज्या (मीटर)","ja":"半径（メートル）","pt":"Raio (metros)","ru":"Радиус (метры)","tr":"Yarıçap (metre)","zh-rCN":"半径（米）"},
 "map_radius_range": {"ar":"النطاق المسموح: من %1$d إلى %2$d متر","de":"Erlaubter Bereich: %1$d bis %2$d Meter","es":"Rango permitido: de %1$d a %2$d metros","fr":"Plage autorisée : de %1$d à %2$d mètres","hi":"अनुमत सीमा: %1$d से %2$d मीटर","ja":"許容範囲：%1$d〜%2$d メートル","pt":"Faixa permitida: de %1$d a %2$d metros","ru":"Допустимый диапазон: от %1$d до %2$d метров","tr":"İzin verilen aralık: %1$d ile %2$d metre","zh-rCN":"允许范围：%1$d 到 %2$d 米"},
 "map_save_location": {"ar":"حفظ الموقع","de":"Standort speichern","es":"Guardar ubicación","fr":"Enregistrer le lieu","hi":"स्थान सहेजें","ja":"場所を保存","pt":"Salvar local","ru":"Сохранить место","tr":"Konumu kaydet","zh-rCN":"保存位置"},
 "map_selected_location": {"ar":"الموقع المحدد","de":"Gewählter Standort","es":"Ubicación seleccionada","fr":"Lieu sélectionné","hi":"चयनित स्थान","ja":"選択した場所","pt":"Local selecionado","ru":"Выбранное место","tr":"Seçilen konum","zh-rCN":"已选位置"},
 "rom_setting_pick_key": {"ar":"اختر مفتاح إعداد (مصنّف)","de":"Einstellungsschlüssel wählen (kategorisiert)","es":"Elegir clave de ajuste (por categorías)","fr":"Choisir une clé de réglage (par catégories)","hi":"सेटिंग कुंजी चुनें (वर्गीकृत)","ja":"設定キーを選択（カテゴリ別）","pt":"Escolher chave de configuração (por categorias)","ru":"Выбрать ключ настройки (по категориям)","tr":"Ayar anahtarı seç (kategorili)","zh-rCN":"选择设置键（按类别）"},
 "rom_setting_trigger_hint": {"ar":"يُفعَّل عند تغيّر مفتاح نظام (Evolver) إلى القيمة المستهدفة. اختر مفتاحًا من جهازك — دون كتابة.","de":"Löst aus, wenn ein System-(Evolver-)Schlüssel auf den Zielwert wechselt. Wähle einen Schlüssel von deinem Gerät — ohne Tippen.","es":"Se activa cuando una clave del sistema (Evolver) cambia al valor objetivo. Elige una clave de tu dispositivo — sin escribir.","fr":"Se déclenche quand une clé système (Evolver) passe à la valeur cible. Choisissez une clé de votre appareil — sans saisie.","hi":"सिस्टम (Evolver) कुंजी के लक्ष्य मान पर बदलने पर चलता है। अपने डिवाइस से कुंजी चुनें — टाइपिंग की ज़रूरत नहीं।","ja":"システム（Evolver）キーが目標値に変わると発火します。デバイスからキーを選択 — 入力は不要です。","pt":"Dispara quando uma chave do sistema (Evolver) muda para o valor alvo. Escolha uma chave do seu dispositivo — sem digitação.","ru":"Срабатывает, когда системный ключ (Evolver) меняется на целевое значение. Выберите ключ с устройства — без ввода текста.","tr":"Bir sistem (Evolver) anahtarı hedef değere değiştiğinde tetiklenir. Cihazınızdan bir anahtar seçin — yazmaya gerek yok.","zh-rCN":"当系统（Evolver）键变更为目标值时触发。从设备中选择键 — 无需输入。"},
 "rom_setting_trigger_title": {"ar":"تغيير إعداد ROM","de":"ROM-Einstellungsänderung","es":"Cambio de ajuste de ROM","fr":"Changement de réglage ROM","hi":"ROM सेटिंग बदलाव","ja":"ROM 設定の変更","pt":"Mudança de configuração da ROM","ru":"Изменение настройки ROM","tr":"ROM ayarı değişikliği","zh-rCN":"ROM 设置变更"},
 "settings_security": {"ar":"الأمان","de":"Sicherheit","es":"Seguridad","fr":"Sécurité","hi":"सुरक्षा","ja":"セキュリティ","pt":"Segurança","ru":"Безопасность","tr":"Güvenlik","zh-rCN":"安全"},
 "end_behavior_add_first": {"ar":"أضف إجراءات أولًا لاختيار ما يحدث عند انتهاء المهمة","de":"Füge zuerst Aktionen hinzu, um das Endverhalten zu wählen","es":"Añade acciones primero para elegir qué ocurre al terminar la tarea","fr":"Ajoutez d\u2019abord des actions pour choisir le comportement de fin","hi":"कार्य समाप्त होने पर क्या होगा चुनने के लिए पहले क्रियाएँ जोड़ें","ja":"終了時の動作を選ぶには、先にアクションを追加してください","pt":"Adicione ações primeiro para escolher o que acontece ao terminar a tarefa","ru":"Сначала добавьте действия, чтобы выбрать поведение при завершении","tr":"Görev bittiğinde ne olacağını seçmek için önce eylem ekleyin","zh-rCN":"请先添加操作，再选择任务结束时的行为"},
 "end_behavior_none_supported": {"ar":"لا يوجد إجراء يدعم سلوك الانتهاء — أضف إجراءً مثل الواي فاي أو السطوع","de":"Keine Aktion unterstützt ein Endverhalten — füge z. B. WLAN oder Helligkeit hinzu","es":"Ninguna acción admite comportamiento final — añade una como Wi-Fi o brillo","fr":"Aucune action ne prend en charge un comportement de fin — ajoutez-en une comme le Wi-Fi ou la luminosité","hi":"कोई क्रिया समाप्ति व्यवहार का समर्थन नहीं करती — Wi-Fi या ब्राइटनेस जैसी जोड़ें","ja":"終了動作に対応するアクションがありません — Wi-Fi や明るさなどを追加してください","pt":"Nenhuma ação suporta comportamento final — adicione uma como Wi-Fi ou brilho","ru":"Ни одно действие не поддерживает поведение завершения — добавьте, например, Wi-Fi или яркость","tr":"Hiçbir eylem bitiş davranışını desteklemiyor — Wi-Fi veya parlaklık gibi bir tane ekleyin","zh-rCN":"没有操作支持结束行为 — 请添加如 Wi-Fi 或亮度之类的操作"},
 "wait_custom_duration": {"ar":"مدة مخصصة (بالثواني)","de":"Eigene Dauer (Sekunden)","es":"Duración personalizada (segundos)","fr":"Durée personnalisée (secondes)","hi":"कस्टम अवधि (सेकंड)","ja":"カスタム時間（秒）","pt":"Duração personalizada (segundos)","ru":"Своя длительность (секунды)","tr":"Özel süre (saniye)","zh-rCN":"自定义时长（秒）"},
 "wait_quick_timer": {"ar":"مؤقت سريع","de":"Schnell-Timer","es":"Temporizador rápido","fr":"Minuteur rapide","hi":"क्विक टाइमर","ja":"クイックタイマー","pt":"Temporizador rápido","ru":"Быстрый таймер","tr":"Hızlı zamanlayıcı","zh-rCN":"快速计时"},
 "wait_range_hint": {"ar":"من ثانية واحدة إلى 24 ساعة","de":"1 Sekunde bis 24 Stunden","es":"De 1 segundo a 24 horas","fr":"De 1 seconde à 24 heures","hi":"1 सेकंड से 24 घंटे","ja":"1秒〜24時間","pt":"De 1 segundo a 24 horas","ru":"От 1 секунды до 24 часов","tr":"1 saniye ile 24 saat arası","zh-rCN":"1 秒到 24 小时"},
}

def esc(t: str) -> str:
    return t.replace("&", "&amp;")

LOCS = ["values-ar","values-de","values-es","values-fr","values-hi","values-ja","values-pt","values-ru","values-tr","values-zh-rCN"]
for key, mapping in T.items():
    for loc in LOCS:
        text = mapping.get(loc.removeprefix("values-"))
        if text is None:
            continue
        suffix = loc.removeprefix("values-")
        path = f"feature/automation-builder/src/main/res/{loc}/strings.xml"
        with open(path, encoding="utf-8") as f:
            content = f.read()
        pattern = rf'([ \t]*<string name="{key}">).*?(</string>\n)'
        new_line = rf'\g<1>{esc(text)}\g<2>'
        content, n = re.subn(pattern, new_line, content, count=1)
        if n:
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(content)
print(f"translated {len(T)} keys across {len(LOCS)} locales")
