#!/usr/bin/env bash
# Generates the project release signing credentials (the 4 keys) once and
# optionally uploads them to GitHub Actions secrets so CI signs release APKs
# with the SAME stable key as local builds. A stable key is what lets users
# install updates on top of each other without uninstalling.
#
# Usage:
#   ./scripts/setup-signing.sh             generate locally (idempotent)
#   ./scripts/setup-signing.sh --upload    also push secrets to GitHub (needs gh)
#
# Outputs (both gitignored — never commit them):
#   keystore/nexaflow-release.jks     the keystore (the signing key itself)
#   keystore/keystore.properties      storeFile / storePassword / keyAlias / keyPassword
#
# The CI workflow (android-ci.yml) reads these repository secrets:
#   NEXAFLOW_KEYSTORE_BASE64, NEXAFLOW_KEYSTORE_PASSWORD,
#   NEXAFLOW_KEY_ALIAS, NEXAFLOW_KEY_PASSWORD
#
# IMPORTANT: the key is generated ONCE. Re-running never regenerates it, so a
# key that already signed an installed app keeps signing its updates (Android
# only installs an update over the same signing certificate).
set -euo pipefail

REPO="${GITHUB_REPOSITORY:-Alaa91H/NexaFlow}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KEYSTORE_DIR="$ROOT/keystore"
KEYSTORE="$KEYSTORE_DIR/nexaflow-release.jks"
PROPS="$KEYSTORE_DIR/keystore.properties"
ALIAS="nexaflow"
UPLOAD=0

for arg in "$@"; do
    case "$arg" in
        --upload|-u) UPLOAD=1 ;;
        --help|-h) sed -n '2,24p' "$0"; exit 0 ;;
    esac
done

# --- locate keytool ---------------------------------------------------------
KEYTOOL=""
if command -v keytool >/dev/null 2>&1; then
    KEYTOOL="keytool"
elif [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/keytool" ]; then
    KEYTOOL="$JAVA_HOME/bin/keytool"
else
    echo "keytool not found. Install a JDK and set JAVA_HOME (or add keytool to PATH)." >&2
    exit 1
fi

mkdir -p "$KEYSTORE_DIR"

# --- random password without shell-breaking characters ----------------------
random_password() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 24
    else
        od -An -tx1 -N24 /dev/urandom | tr -d ' \n'
    fi
}

PASS=""

# --- generate exactly once ---------------------------------------------------
# PKCS12 (the modern Android signing format) uses ONE password for both the
# store and the key, so storePassword == keyPassword below.
if [ -f "$KEYSTORE" ]; then
    echo "Keystore already exists at $KEYSTORE — leaving it untouched."
    echo "(Regenerating would break update-over-install for existing users.)"
    PASS="$(grep -E '^storePassword=' "$PROPS" 2>/dev/null | cut -d= -f2- || true)"
    PROPS_ALIAS="$(grep -E '^keyAlias=' "$PROPS" 2>/dev/null | cut -d= -f2- || true)"
    [ -n "$PROPS_ALIAS" ] && ALIAS="$PROPS_ALIAS"
    if [ -z "$PASS" ]; then
        echo "ERROR: keystore exists but $PROPS is missing its passwords." >&2
        echo "Fill storePassword/keyPassword there and re-run to upload to GitHub." >&2
        exit 1
    fi
else
    PASS="$(random_password)"
    "$KEYTOOL" -genkeypair -v \
        -keystore "$KEYSTORE" \
        -storepass "$PASS" \
        -keypass "$PASS" \
        -alias "$ALIAS" \
        -keyalg RSA -keysize 4096 \
        -validity 10000 \
        -dname "CN=NexaFlow, OU=Mobile, O=NexaFlow, L=Internet, C=US"
    echo "Generated $KEYSTORE"
fi

# --- (re)write keystore.properties, preserving an existing mapsApiKey -------
MAPS_KEY="$(grep -E '^mapsApiKey=' "$PROPS" 2>/dev/null | cut -d= -f2- || true)"
cat > "$PROPS" <<EOF
# Generated by scripts/setup-signing.sh — gitignored, never commit.
storeFile=keystore/nexaflow-release.jks
storePassword=$PASS
keyAlias=$ALIAS
keyPassword=$PASS
EOF
if [ -n "$MAPS_KEY" ]; then
    echo "mapsApiKey=$MAPS_KEY" >> "$PROPS"
fi
echo "Wrote $PROPS"

# --- optionally upload to GitHub Actions secrets -----------------------------
if [ "$UPLOAD" -eq 1 ]; then
    if ! command -v gh >/dev/null 2>&1; then
        echo "gh CLI not found. Install it from https://cli.github.com" >&2
        exit 1
    fi
    gh auth status >/dev/null 2>&1 || {
        echo "gh is not authenticated. Run: gh auth login" >&2
        exit 1
    }
    printf '%s' "$(base64 "$KEYSTORE" | tr -d '\n')" | gh secret set NEXAFLOW_KEYSTORE_BASE64 --repo "$REPO"
    gh secret set NEXAFLOW_KEYSTORE_PASSWORD --repo "$REPO" --body "$PASS"
    gh secret set NEXAFLOW_KEY_ALIAS --repo "$REPO" --body "$ALIAS"
    gh secret set NEXAFLOW_KEY_PASSWORD --repo "$REPO" --body "$PASS"
    echo "Signing secrets configured for $REPO"
fi

echo "Done. Next release builds sign with the stable key (updates install over each other)."
