#!/usr/bin/env python3
"""One-shot applier: translate every flagged untranslated English copy.

For every locale string whose value equals the English default AND whose
English value has a curated translation below, rewrite the locale value.
Values are matched EXACTLY (full strings extracted from the defaults), so
this never clobbers real translations. XML escaping follows Android rules
(literal apostrophes become \\').

Words that happen to be identical to English in some target languages
(Test/Manual/Condition in fr-tr, App/Text/Start in de, ...) are whitelisted
in the auditor's IDENTICAL_OK, not here.
"""
from __future__ import annotations

import glob
import re
import sys
from pathlib import Path
from xml.etree import ElementTree

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# English value -> per-locale translations. Keyed by the FULL English value.
T: dict[str, dict[str, str]] = {
    "Run linked task?": {
        "ar": "تشغيل المهمة المرتبطة؟", "de": "Verknüpfte Aufgabe ausführen?",
        "es": "¿Ejecutar la tarea vinculada?", "fr": "Exécuter la tâche liée ?",
        "hi": "लिंक किया कार्य चलाएँ?", "ja": "リンクされたタスクを実行しますか？",
        "pt": "Executar a tarefa vinculada?", "ru": "Запустить связанную задачу?",
        "tr": "Bağlantılı görev çalıştırılsın mı?", "zh-rCN": "运行关联的任务？",
    },
    "Run": {
        "ar": "تشغيل", "de": "Ausführen", "es": "Ejecutar", "fr": "Exécuter",
        "hi": "चलाएँ", "ja": "実行", "pt": "Executar", "ru": "Запустить",
        "tr": "Çalıştır", "zh-rCN": "运行",
    },
    "An external link requests running %1$s. Review the task before confirming.": {
        "ar": "طلب رابط خارجي تشغيل %1$s. راجع المهمة قبل التأكيد.",
        "de": "Ein externer Link möchte %1$s ausführen. Prüfe die Aufgabe, bevor du bestätigst.",
        "es": "Un enlace externo solicita ejecutar %1$s. Revisa la tarea antes de confirmar.",
        "fr": "Un lien externe demande d'exécuter %1$s. Vérifiez la tâche avant de confirmer.",
        "hi": "एक बाहरी लिंक %1$s चलाने का अनुरोध करता है। पुष्टि करने से पहले कार्य की समीक्षा करें।",
        "ja": "外部リンクが %1$s の実行を要求しています。確認する前にタスクを見直してください。",
        "pt": "Um link externo solicita executar %1$s. Revise a tarefa antes de confirmar.",
        "ru": "Внешняя ссылка запрашивает запуск %1$s. Проверьте задачу перед подтверждением.",
        "tr": "Harici bir bağlantı %1$s çalıştırmayı istiyor. Onaylamadan önce görevi inceleyin.",
        "zh-rCN": "外部链接请求运行 %1$s。确认前请先检查该任务。",
    },
    "Triggers or conditions are not satisfied. Only the end behavior (when the task ends) was completed.": {
        "ar": "لم تتحقق المشغلات أو الشروط. نُفِّذ السلوك الختامي فقط (عند انتهاء المهمة).",
        "de": "Trigger oder Bedingungen sind nicht erfüllt. Nur das Endverhalten (beim Aufgabenende) wurde ausgeführt.",
        "es": "Los iniciadores o condiciones no se cumplieron. Solo se ejecutó el comportamiento final (al terminar la tarea).",
        "fr": "Déclencheurs ou conditions non satisfaits. Seul le comportement final (à la fin de la tâche) a été exécuté.",
        "hi": "ट्रिगर या शर्तें पूरी नहीं हुईं। केवल अंतिम व्यवहार (कार्य समाप्त होने पर) पूरा हुआ।",
        "ja": "トリガーまたは条件が満たされませんでした。終了動作（タスク終了時）のみ実行されました。",
        "pt": "Gatilhos ou condições não satisfeitos. Apenas o comportamento final (ao término da tarefa) foi executado.",
        "ru": "Триггеры или условия не выполнены. Выполнено только конечное поведение (при завершении задачи).",
        "tr": "Tetikleyiciler veya koşullar sağlanmadı. Yalnızca bitiş davranışı (görev bittiğinde) tamamlandı.",
        "zh-rCN": "触发器或条件未满足。仅执行了结束行为（任务结束时）。",
    },
    "Triggers or conditions of the task are not satisfied, so it cannot run now. No end behavior is configured.": {
        "ar": "لم تتحقق مشغلات المهمة أو شروطها، لذا لا يمكنها التشغيل الآن. لا سلوك ختامي مُهيأ.",
        "de": "Trigger oder Bedingungen der Aufgabe sind nicht erfüllt, sie kann jetzt nicht laufen. Kein Endverhalten konfiguriert.",
        "es": "Los iniciadores o condiciones de la tarea no se cumplieron, así que no puede ejecutarse ahora. No hay comportamiento final configurado.",
        "fr": "Déclencheurs ou conditions de la tâche non satisfaits, elle ne peut donc pas s'exécuter maintenant. Aucun comportement final n'est configuré.",
        "hi": "कार्य के ट्रिगर या शर्तें पूरी नहीं हुईं, इसलिए यह अभी नहीं चल सकता। कोई अंतिम व्यवहार कॉन्फ़िगर नहीं है।",
        "ja": "タスクのトリガーまたは条件が満たされず、現在実行できません。終了動作は設定されていません。",
        "pt": "Os gatilhos ou condições da tarefa não foram satisfeitos, portanto não pode ser executada agora. Nenhum comportamento final configurado.",
        "ru": "Триггеры или условия задачи не выполнены, поэтому сейчас она не может запуститься. Конечное поведение не настроено.",
        "tr": "Görevin tetikleyicileri veya koşulları sağlanmadı, bu yüzden şu anda çalışamaz. Bitiş davranışı yapılandırılmamış.",
        "zh-rCN": "任务的触发器或条件未满足，因此现在无法运行。未配置结束行为。",
    },
    "Triggers or conditions of the task are not satisfied, so it cannot run now. The end behavior could not be completed.": {
        "ar": "لم تتحقق مشغلات المهمة أو شروطها، لذا لا يمكنها التشغيل الآن. تعذّر إكمال السلوك الختامي.",
        "de": "Trigger oder Bedingungen der Aufgabe sind nicht erfüllt, sie kann jetzt nicht laufen. Das Endverhalten konnte nicht abgeschlossen werden.",
        "es": "Los iniciadores o condiciones de la tarea no se cumplieron, así que no puede ejecutarse ahora. No se pudo completar el comportamiento final.",
        "fr": "Déclencheurs ou conditions de la tâche non satisfaits, elle ne peut donc pas s'exécuter maintenant. Le comportement final n'a pas pu être mené à terme.",
        "hi": "कार्य के ट्रिगर या शर्तें पूरी नहीं हुईं, इसलिए यह अभी नहीं चल सकता। अंतिम व्यवहार पूरा नहीं हो सका।",
        "ja": "タスクのトリガーまたは条件が満たされず、現在実行できません。終了動作を完了できませんでした。",
        "pt": "Os gatilhos ou condições da tarefa não foram satisfeitos, portanto não pode ser executada agora. O comportamento final não pôde ser concluído.",
        "ru": "Триггеры или условия задачи не выполнены, поэтому сейчас она не может запуститься. Конечное поведение не удалось завершить.",
        "tr": "Görevin tetikleyicileri veya koşulları sağlanmadı, bu yüzden şu anda çalışamaz. Bitiş davranışı tamamlanamadı.",
        "zh-rCN": "任务的触发器或条件未满足，因此现在无法运行。结束行为未能完成。",
    },
    "Notifications": {
        "ar": "الإشعارات", "de": "Benachrichtigungen", "es": "Notificaciones",
        "hi": "सूचनाएँ", "ja": "通知", "ru": "Уведомления",
        "tr": "Bildirimler", "zh-rCN": "通知",
    },
    "Message": {
        "ar": "الرسالة", "de": "Nachricht", "es": "Mensaje", "fr": "Message",
        "hi": "संदेश", "ja": "メッセージ", "pt": "Mensagem", "ru": "Сообщение",
        "tr": "Mesaj", "zh-rCN": "消息",
    },
    "On": {
        "ar": "تشغيل", "de": "An", "es": "Activado", "fr": "Activé",
        "hi": "चालू", "ja": "オン", "pt": "Ligado", "ru": "Вкл.",
        "tr": "Açık", "zh-rCN": "开",
    },
    "Timeout": {
        "ar": "المهلة", "de": "Timeout", "es": "Tiempo de espera",
        "fr": "Délai", "hi": "टाइमआउट", "ja": "タイムアウト",
        "pt": "Tempo limite", "ru": "Таймаут", "tr": "Zaman aşımı",
        "zh-rCN": "超时",
    },
    "Any device": {
        "ar": "أي جهاز", "de": "Beliebiges Gerät", "es": "Cualquier dispositivo",
        "fr": "N'importe quel appareil", "hi": "कोई भी डिवाइस", "ja": "任意のデバイス",
        "pt": "Qualquer dispositivo", "ru": "Любое устройство", "tr": "Herhangi bir cihaz",
        "zh-rCN": "任意设备",
    },
    "Any Bluetooth device": {
        "ar": "أي جهاز بلوتوث", "de": "Beliebiges Bluetooth-Gerät",
        "es": "Cualquier dispositivo Bluetooth", "fr": "N'importe quel appareil Bluetooth",
        "hi": "कोई भी ब्लूटूथ डिवाइस", "ja": "任意のBluetoothデバイス",
        "pt": "Qualquer dispositivo Bluetooth", "ru": "Любое Bluetooth-устройство",
        "tr": "Herhangi bir Bluetooth cihazı", "zh-rCN": "任意蓝牙设备",
    },
    "Caller number": {
        "ar": "رقم المتصل", "de": "Anrufernummer", "es": "Número del llamante",
        "fr": "Numéro de l'appelant", "hi": "कॉलर नंबर", "ja": "発信者番号",
        "pt": "Número do chamador", "ru": "Номер звонящего", "tr": "Arayan numarası",
        "zh-rCN": "来电号码",
    },
    "Matches the caller number, not a message text.": {
        "ar": "يطابق رقم المتصل، لا نص رسالة.",
        "de": "Entspricht der Anrufernummer, nicht einem Nachrichtentext.",
        "es": "Coincide con el número del llamante, no con un texto de mensaje.",
        "fr": "Correspond au numéro de l'appelant, pas à un texte de message.",
        "hi": "कॉलर नंबर से मेल खाता है, संदेश पाठ से नहीं।",
        "ja": "メッセージ本文ではなく発信者番号に一致します。",
        "pt": "Corresponde ao número do chamador, não ao texto de uma mensagem.",
        "ru": "Совпадает с номером звонящего, а не с текстом сообщения.",
        "tr": "Arayan numarasıyla eşleşir, mesaj metniyle değil.",
        "zh-rCN": "匹配来电号码，而非消息文本。",
    },
    "Any number": {
        "ar": "أي رقم", "de": "Beliebige Nummer", "es": "Cualquier número",
        "fr": "N'importe quel numéro", "hi": "कोई भी नंबर", "ja": "任意の番号",
        "pt": "Qualquer número", "ru": "Любой номер", "tr": "Herhangi bir numara",
        "zh-rCN": "任意号码",
    },
    "Contacts": {
        "ar": "جهات الاتصال", "de": "Kontakte", "es": "Contactos", "fr": "Contacts",
        "hi": "संपर्क", "ja": "連絡先", "pt": "Contatos", "ru": "Контакты",
        "tr": "Kişiler", "zh-rCN": "联系人",
    },
    "Contact": {
        "ar": "جهة اتصال", "de": "Kontakt", "es": "Contacto", "fr": "Contact",
        "hi": "संपर्क", "ja": "連絡先", "pt": "Contato", "ru": "Контакт",
        "tr": "Kişi", "zh-rCN": "联系人",
    },
    "Apps": {
        "ar": "التطبيقات", "de": "Apps", "es": "Aplicaciones", "fr": "Applications",
        "hi": "ऐप्स", "ja": "アプリ", "pt": "Aplicativos", "ru": "Приложения",
        "tr": "Uygulamalar", "zh-rCN": "应用",
    },
    "System": {
        "ar": "النظام", "de": "System", "es": "Sistema", "fr": "Système",
        "hi": "सिस्टम", "ja": "システム", "pt": "Sistema", "ru": "Система",
        "tr": "Sistem", "zh-rCN": "系统",
    },
    "Hotspot": {
        "ar": "نقطة الاتصال", "de": "Hotspot", "es": "Punto de acceso",
        "fr": "Point d'accès", "hi": "हॉटस्पॉट", "ja": "ホットスポット",
        "pt": "Ponto de acesso", "ru": "Точка доступа", "tr": "Erişim noktası",
        "zh-rCN": "热点",
    },
    "Screenshot": {
        "ar": "لقطة شاشة", "de": "Screenshot", "es": "Captura de pantalla",
        "fr": "Capture d'écran", "hi": "स्क्रीनशॉट", "ja": "スクリーンショット",
        "pt": "Captura de tela", "ru": "Скриншот", "tr": "Ekran görüntüsü",
        "zh-rCN": "截图",
    },
    "Animations": {
        "ar": "الرسوم المتحركة", "de": "Animationen", "es": "Animaciones",
        "fr": "Animations", "hi": "एनिमेशन", "ja": "アニメーション",
        "pt": "Animações", "ru": "Анимации", "tr": "Animasyonlar",
        "zh-rCN": "动画",
    },
    "Volume": {
        "ar": "مستوى الصوت", "de": "Lautstärke", "es": "Volumen", "fr": "Volume",
        "hi": "वॉल्यूम", "ja": "音量", "pt": "Volume", "ru": "Громкость",
        "tr": "Ses", "zh-rCN": "音量",
    },
    "Volume %1$d": {
        "ar": "مستوى الصوت %1$d", "de": "Lautstärke %1$d", "es": "Volumen %1$d",
        "fr": "Volume %1$d", "hi": "वॉल्यूम %1$d", "ja": "音量 %1$d",
        "pt": "Volume %1$d", "ru": "Громкость %1$d", "tr": "Ses %1$d",
        "zh-rCN": "音量 %1$d",
    },
    "Volume: %1$d": {
        "ar": "مستوى الصوت: %1$d", "de": "Lautstärke: %1$d", "es": "Volumen: %1$d",
        "fr": "Volume : %1$d", "hi": "वॉल्यूम: %1$d", "ja": "音量: %1$d",
        "pt": "Volume: %1$d", "ru": "Громкость: %1$d", "tr": "Ses: %1$d",
        "zh-rCN": "音量: %1$d",
    },
    "Alarm": {
        "ar": "المنبّه", "de": "Alarm", "es": "Alarma", "fr": "Alarme",
        "hi": "अलार्म", "ja": "アラーム", "pt": "Alarme", "ru": "Сигнал",
        "tr": "Alarm", "zh-rCN": "闹钟",
    },
    "SMS": {
        "ar": "رسائل SMS", "zh-rCN": "短信",
    },
    "Webhook": {
        "ar": "Webhook", "ru": "Вебхук",
    },
    "App": {
        "ar": "التطبيق", "de": "App", "es": "Aplicación", "fr": "Application",
        "hi": "ऐप", "ja": "アプリ", "pt": "Aplicativo", "ru": "Приложение",
        "tr": "Uygulama", "zh-rCN": "应用",
    },
    "Sensor": {
        "ar": "المستشعر", "de": "Sensor", "es": "Sensor", "fr": "Capteur",
        "hi": "सेंसर", "ja": "センサー", "pt": "Sensor", "ru": "Датчик",
        "tr": "Sensör", "zh-rCN": "传感器",
    },
    "Mobile data connected": {
        "ar": "بيانات الجوال متصلة", "de": "Mobile Daten verbunden",
        "es": "Datos móviles conectados", "fr": "Données mobiles connectées",
        "hi": "मोबाइल डेटा कनेक्टेड", "ja": "モバイルデータ接続済み",
        "pt": "Dados móveis conectados", "ru": "Мобильные данные подключены",
        "tr": "Mobil veri bağlı", "zh-rCN": "移动数据已连接",
    },
    "Runs when mobile data is the active network (or not)": {
        "ar": "يعمل عندما تكون بيانات الجوال هي الشبكة النشطة (أو لا)",
        "de": "Läuft, wenn mobile Daten das aktive Netzwerk sind (oder nicht)",
        "es": "Se ejecuta cuando los datos móviles son la red activa (o no)",
        "fr": "S'exécute quand les données mobiles sont le réseau actif (ou non)",
        "hi": "तब चलता है जब मोबाइल डेटा सक्रिय नेटवर्क हो (या न हो)",
        "ja": "モバイルデータがアクティブなネットワークのときに実行（またはその逆）",
        "pt": "É executado quando os dados móveis são a rede ativa (ou não)",
        "ru": "Срабатывает, когда мобильные данные — активная сеть (или нет)",
        "tr": "Mobil veri etkin ağ olduğunda çalışır (veya olmazsa)",
        "zh-rCN": "移动数据为活动网络时运行（或相反）",
    },
    "Wi-Fi connected": {
        "ar": "Wi-Fi متصل", "de": "WLAN verbunden", "es": "Wi-Fi conectado",
        "fr": "Wi-Fi connecté", "hi": "Wi-Fi कनेक्टेड", "ja": "Wi-Fi 接続済み",
        "pt": "Wi-Fi conectado", "ru": "Wi-Fi подключён", "tr": "Wi-Fi bağlı",
        "zh-rCN": "Wi-Fi 已连接",
    },
    "Runs when the device connects to Wi-Fi (or disconnects)": {
        "ar": "يعمل عند اتصال الجهاز بـ Wi-Fi (أو انفصاله)",
        "de": "Läuft, wenn das Gerät WLAN verbindet (oder trennt)",
        "es": "Se ejecuta cuando el dispositivo se conecta a Wi-Fi (o se desconecta)",
        "fr": "S'exécute quand l'appareil se connecte au Wi-Fi (ou s'en déconnecte)",
        "hi": "तब चलता है जब डिवाइस Wi-Fi से कनेक्ट हो (या डिस्कनेक्ट हो)",
        "ja": "デバイスが Wi-Fi に接続したとき（または切断したとき）に実行",
        "pt": "É executado quando o dispositivo conecta ao Wi-Fi (ou desconecta)",
        "ru": "Срабатывает при подключении устройства к Wi-Fi (или отключении)",
        "tr": "Cihaz Wi-Fi'ye bağlandığında (veya koptuğunda) çalışır",
        "zh-rCN": "设备连接到 Wi-Fi 时运行（或断开时）",
    },
    "Token (required)": {
        "ar": "الرمز (مطلوب)", "de": "Token (erforderlich)", "es": "Token (obligatorio)",
        "fr": "Jeton (obligatoire)", "hi": "टोकन (आवश्यक)", "ja": "トークン（必須）",
        "pt": "Token (obrigatório)", "ru": "Токен (обязательно)",
        "tr": "Belirteç (gerekli)", "zh-rCN": "令牌（必填）",
    },
    "Required secret; blank tokens cannot run tasks": {
        "ar": "سر مطلوب؛ الرموز الفارغة لا يمكنها تشغيل المهام",
        "de": "Erforderliches Geheimnis; leere Tokens können Aufgaben nicht ausführen",
        "es": "Secreto obligatorio; los tokens vacíos no pueden ejecutar tareas",
        "fr": "Secret obligatoire ; les jetons vides ne peuvent pas exécuter de tâches",
        "hi": "आवश्यक गुप्त कुंजी; खाली टोकन कार्य नहीं चला सकते",
        "ja": "必須のシークレット。空のトークンはタスクを実行できません",
        "pt": "Segredo obrigatório; tokens vazios não podem executar tarefas",
        "ru": "Обязательный секрет; пустые токены не могут запускать задачи",
        "tr": "Gerekli gizli anahtar; boş belirteçler görev çalıştıramaz",
        "zh-rCN": "必需的密钥；空白令牌无法运行任务",
    },
    "This webhook has no token and cannot run. Review the task, then generate a token and update its caller.": {
        "ar": "هذا الويب هوك بلا رمز ولا يمكنه التشغيل. راجع المهمة، ثم أنشئ رمزًا وحدّث مستدعيه.",
        "de": "Dieser Webhook hat keinen Token und kann nicht laufen. Prüfe die Aufgabe, generiere dann einen Token und aktualisiere den Aufrufer.",
        "es": "Este webhook no tiene token y no puede ejecutarse. Revisa la tarea, luego genera un token y actualiza su invocador.",
        "fr": "Ce webhook n'a pas de jeton et ne peut pas s'exécuter. Vérifiez la tâche, puis générez un jeton et mettez à jour son appelant.",
        "hi": "इस वेबहुक में टोकन नहीं है और यह नहीं चल सकता। कार्य की समीक्षा करें, फिर टोकन जनरेट करें और उसका कॉलर अपडेट करें।",
        "ja": "このWebhookにはトークンがなく実行できません。タスクを確認し、トークンを生成して呼び出し元を更新してください。",
        "pt": "Este webhook não tem token e não pode ser executado. Revise a tarefa, depois gere um token e atualize o chamador.",
        "ru": "У этого вебхука нет токена, запуск невозможен. Проверьте задачу, затем создайте токен и обновите вызывающую сторону.",
        "tr": "Bu webhook'un belirteci yok ve çalışamaz. Görevi inceleyin, ardından bir belirteç oluşturup çağırıcıyı güncelleyin.",
        "zh-rCN": "此 Webhook 没有令牌，无法运行。请检查任务，然后生成令牌并更新其调用方。",
    },
    "Generate required token": {
        "ar": "إنشاء الرمز المطلوب", "de": "Erforderlichen Token generieren",
        "es": "Generar token obligatorio", "fr": "Générer le jeton requis",
        "hi": "आवश्यक टोकन जनरेट करें", "ja": "必須トークンを生成",
        "pt": "Gerar token obrigatório", "ru": "Сгенерировать обязательный токен",
        "tr": "Gerekli belirteci oluştur", "zh-rCN": "生成必需令牌",
    },
    "External task links": {
        "ar": "روابط المهام الخارجية", "de": "Externe Aufgabenlinks",
        "es": "Enlaces de tareas externos", "fr": "Liens de tâches externes",
        "hi": "बाहरी कार्य लिंक", "ja": "外部タスクリンク",
        "pt": "Links de tarefas externos", "ru": "Внешние ссылки задач",
        "tr": "Harici görev bağlantıları", "zh-rCN": "外部任务链接",
    },
    "Enable links only for trusted recipients. Opening a link always asks before running. Rotating or revoking invalidates old links and shortcuts.": {
        "ar": "فعّل الروابط للمستلمين الموثوقين فقط. فتح أي رابط يطلب التأكيد قبل التشغيل دائمًا. التجديد أو الإبطال يُلغي الروابط والاختصارات القديمة.",
        "de": "Links nur für vertrauenswürdige Empfänger aktivieren. Das Öffnen eines Links fragt immer vor dem Ausführen. Rotieren oder Widerrufen macht alte Links und Shortcuts ungültig.",
        "es": "Activa los enlaces solo para destinatarios de confianza. Abrir un enlace siempre pide confirmación antes de ejecutar. Rotar o revocar invalida los enlaces y accesos antiguos.",
        "fr": "N'activez les liens que pour des destinataires de confiance. Ouvrir un lien demande toujours confirmation avant exécution. Renouveler ou révoquer invalide les anciens liens et raccourcis.",
        "hi": "लिंक केवल भरोसेमंद प्राप्तकर्ताओं के लिए सक्षम करें। लिंक खोलने पर चलाने से पहले हमेशा पुष्टि माँगी जाती है। रोटेट या रद्द करने से पुराने लिंक और शॉर्टकट अमान्य हो जाते हैं।",
        "ja": "信頼できる相手にのみリンクを有効にしてください。リンクを開くと実行前に必ず確認します。更新や取り消しで古いリンクとショートカットは無効になります。",
        "pt": "Ative os links apenas para destinatários confiáveis. Abrir um link sempre pede confirmação antes de executar. Rotacionar ou revogar invalida links e atalhos antigos.",
        "ru": "Включайте ссылки только для доверенных получателей. Открытие ссылки всегда запрашивает подтверждение перед запуском. Смена или отзыв делает старые ссылки и ярлыки недействительными.",
        "tr": "Bağlantıları yalnızca güvenilir alıcılar için etkinleştirin. Bir bağlantıyı açmak çalıştırmadan önce her zaman onay ister. Yenileme veya iptal, eski bağlantı ve kısayolları geçersiz kılar.",
        "zh-rCN": "仅为信任的接收者启用链接。打开链接在运行前总是先询问。轮换或撤销会使旧链接和快捷方式失效。",
    },
    "Enable": {
        "ar": "تمكين", "de": "Aktivieren", "es": "Activar", "fr": "Activer",
        "hi": "सक्षम करें", "ja": "有効にする", "pt": "Ativar", "ru": "Включить",
        "tr": "Etkinleştir", "zh-rCN": "启用",
    },
    "Revoke": {
        "ar": "إبطال", "de": "Widerrufen", "es": "Revocar", "fr": "Révoquer",
        "hi": "रद्द करें", "ja": "取り消す", "pt": "Revogar", "ru": "Отозвать",
        "tr": "İptal et", "zh-rCN": "撤销",
    },
    "Rotate token": {
        "ar": "تجديد الرمز", "de": "Token rotieren", "es": "Rotar token",
        "fr": "Renouveler le jeton", "hi": "टोकन रोटेट करें", "ja": "トークンを更新",
        "pt": "Rotacionar token", "ru": "Сменить токен", "tr": "Belirteci yenile",
        "zh-rCN": "轮换令牌",
    },
    "Share link": {
        "ar": "مشاركة الرابط", "de": "Link teilen", "es": "Compartir enlace",
        "fr": "Partager le lien", "hi": "लिंक साझा करें", "ja": "リンクを共有",
        "pt": "Compartilhar link", "ru": "Поделиться ссылкой", "tr": "Bağlantıyı paylaş",
        "zh-rCN": "分享链接",
    },
    "Task details and access links": {
        "ar": "تفاصيل المهمة وروابط الوصول",
        "de": "Aufgabendetails und Zugriffslinks",
        "es": "Detalles de la tarea y enlaces de acceso",
        "fr": "Détails de la tâche et liens d'accès",
        "hi": "कार्य विवरण और एक्सेस लिंक",
        "ja": "タスクの詳細とアクセスリンク",
        "pt": "Detalhes da tarefa e links de acesso",
        "ru": "Сведения о задаче и ссылки доступа",
        "tr": "Görev ayrıntıları ve erişim bağlantıları",
        "zh-rCN": "任务详情和访问链接",
    },
    "Show a message when this task is enabled or disabled": {
        "ar": "إظهار رسالة عند تمكين هذه المهمة أو تعطيلها",
        "de": "Nachricht zeigen, wenn diese Aufgabe ein-/ausgeschaltet wird",
        "es": "Mostrar un mensaje cuando esta tarea se activa o desactiva",
        "fr": "Afficher un message quand cette tâche est activée ou désactivée",
        "hi": "इस कार्य के सक्षम या अक्षम होने पर संदेश दिखाएँ",
        "ja": "このタスクの有効/無効時にメッセージを表示",
        "pt": "Mostrar uma mensagem quando esta tarefa for ativada ou desativada",
        "ru": "Показывать сообщение при включении или отключении этой задачи",
        "tr": "Bu görev etkinleştirildiğinde veya devre dışı bırakıldığında mesaj göster",
        "zh-rCN": "此任务启用或禁用时显示消息",
    },
    "Show toast on toggle": {
        "ar": "إظهار رسالة عند التبديل", "de": "Toast beim Umschalten zeigen",
        "es": "Mostrar toast al alternar", "fr": "Afficher un toast lors du basculement",
        "hi": "टॉगल पर टोस्ट दिखाएँ", "ja": "切り替え時にトーストを表示",
        "pt": "Mostrar toast ao alternar", "ru": "Показывать toast при переключении",
        "tr": "Değişimde toast göster", "zh-rCN": "切换时显示提示",
    },
    "Disabled: %1$s": {
        "ar": "تم التعطيل: %1$s", "de": "Deaktiviert: %1$s", "es": "Desactivada: %1$s",
        "fr": "Désactivée : %1$s", "hi": "अक्षम: %1$s", "ja": "無効: %1$s",
        "pt": "Desativada: %1$s", "ru": "Отключено: %1$s", "tr": "Devre dışı: %1$s",
        "zh-rCN": "已禁用：%1$s",
    },
    "Enabled: %1$s": {
        "ar": "تم التمكين: %1$s", "de": "Aktiviert: %1$s", "es": "Activada: %1$s",
        "fr": "Activée : %1$s", "hi": "सक्षम: %1$s", "ja": "有効: %1$s",
        "pt": "Ativada: %1$s", "ru": "Включено: %1$s", "tr": "Etkin: %1$s",
        "zh-rCN": "已启用：%1$s",
    },
    "Color": {
        "ar": "اللون", "de": "Farbe", "es": "Color", "fr": "Couleur",
        "hi": "रंग", "ja": "色", "pt": "Cor", "ru": "Цвет", "tr": "Renk",
        "zh-rCN": "颜色",
    },
    "General": {
        "ar": "عام", "de": "Allgemein", "es": "General", "fr": "Général",
        "hi": "सामान्य", "ja": "一般", "pt": "Geral", "ru": "Общее",
        "tr": "Genel", "zh-rCN": "常规",
    },
    "Security": {
        "ar": "الأمان", "de": "Sicherheit", "es": "Seguridad", "fr": "Sécurité",
        "hi": "सुरक्षा", "ja": "セキュリティ", "pt": "Segurança", "ru": "Безопасность",
        "tr": "Güvenlik", "zh-rCN": "安全",
    },
    "Manual": {
        "ar": "يدوي", "de": "Manuell", "fr": "Manuel",
        "hi": "मैनुअल", "ja": "手動", "ru": "Вручную",
        "tr": "Manuel", "zh-rCN": "手动",
    },
    "Minutes": {
        "ar": "الدقائق", "de": "Minuten", "es": "Minutos", "fr": "Minutes",
        "hi": "मिनट", "ja": "分", "pt": "Minutos", "ru": "Минуты",
        "tr": "Dakika", "zh-rCN": "分钟",
    },
    "Plugins": {
        "ar": "الإضافات", "de": "Plugins", "es": "Complementos", "fr": "Extensions",
        "hi": "प्लगइन्स", "ja": "プラグイン", "pt": "Plugins", "ru": "Плагины",
        "tr": "Eklentiler", "zh-rCN": "插件",
    },
    "Test": {
        "ar": "اختبار", "de": "Testen", "es": "Probar", "fr": "Tester",
        "hi": "परीक्षण", "ja": "テスト", "pt": "Testar", "ru": "Тест",
        "tr": "Test", "zh-rCN": "测试",
    },
    "Action": {
        "ar": "إجراء", "de": "Aktion", "es": "Acción", "fr": "Action",
        "hi": "क्रिया", "ja": "アクション", "pt": "Ação", "ru": "Действие",
        "tr": "Eylem", "zh-rCN": "动作",
    },
    "Condition": {
        "ar": "شرط", "de": "Bedingung", "es": "Condición", "fr": "Condition",
        "hi": "शर्त", "ja": "条件", "pt": "Condição", "ru": "Условие",
        "tr": "Koşul", "zh-rCN": "条件",
    },
    "Updates": {
        "ar": "التحديثات", "de": "Updates", "es": "Actualizaciones", "fr": "Mises à jour",
        "hi": "अपडेट", "ja": "アップデート", "pt": "Atualizações", "ru": "Обновления",
        "tr": "Güncellemeler", "zh-rCN": "更新",
    },
    "Update": {
        "ar": "تحديث", "de": "Update", "es": "Actualizar", "fr": "Mettre à jour",
        "hi": "अपडेट", "ja": "更新", "pt": "Atualizar", "ru": "Обновить",
        "tr": "Güncelle", "zh-rCN": "更新",
    },
    "Version %1$s": {
        "ar": "الإصدار %1$s", "de": "Version %1$s", "es": "Versión %1$s",
        "fr": "Version %1$s", "hi": "संस्करण %1$s", "ja": "バージョン %1$s",
        "pt": "Versão %1$s", "ru": "Версия %1$s", "tr": "Sürüm %1$s",
        "zh-rCN": "版本 %1$s",
    },
    "Wearables": {
        "ar": "الأجهزة القابلة للارتداء", "de": "Wearables", "es": "Wearables",
        "fr": "Objets connectés", "hi": "वियरेबल", "ja": "ウェアラブル",
        "pt": "Wearables", "ru": "Носимые устройства", "tr": "Giyilebilirler",
        "zh-rCN": "可穿戴设备",
    },
    "Notification": {
        "ar": "الإشعار", "de": "Benachrichtigung", "es": "Notificación",
        "fr": "Notification", "hi": "सूचना", "ja": "通知",
        "pt": "Notificação", "ru": "Уведомление", "tr": "Bildirim",
        "zh-rCN": "通知",
    },
    "Text": {
        "ar": "نص", "de": "Text", "es": "Texto", "fr": "Texte",
        "hi": "पाठ", "ja": "テキスト", "pt": "Texto", "ru": "Текст",
        "tr": "Metin", "zh-rCN": "文本",
    },
    "Start": {
        "ar": "البداية", "de": "Start", "es": "Inicio", "fr": "Départ",
        "hi": "प्रारंभ", "ja": "開始", "pt": "Início", "ru": "Начало",
        "tr": "Başlangıç", "zh-rCN": "开始",
    },
    "Direction": {
        "ar": "الاتجاه", "de": "Richtung", "es": "Dirección", "fr": "Direction",
        "hi": "दिशा", "ja": "方向", "pt": "Direção", "ru": "Направление",
        "tr": "Yön", "zh-rCN": "方向",
    },
    "Portrait": {
        "ar": "عمودي", "de": "Hochformat", "es": "Vertical", "fr": "Portrait",
        "hi": "पोर्ट्रेट", "ja": "縦向き", "pt": "Retrato", "ru": "Портретная",
        "tr": "Dikey", "zh-rCN": "竖屏",
    },
    "occurrences": {
        "ar": "مرة", "de": "Vorkommen", "es": "ocurrencias", "fr": "occurrences",
        "hi": "बार", "ja": "回", "pt": "ocorrências", "ru": "повторений",
        "tr": "tekrar", "zh-rCN": "次",
    },
    "Communication": {
        "ar": "الاتصالات", "de": "Kommunikation", "es": "Comunicación",
        "fr": "Communication", "hi": "संचार", "ja": "通信",
        "pt": "Comunicação", "ru": "Связь", "tr": "İletişim",
        "zh-rCN": "通信",
    },
    "Conditions": {
        "ar": "الشروط", "de": "Bedingungen", "es": "Condiciones", "fr": "Conditions",
        "hi": "शर्तें", "ja": "条件", "pt": "Condições", "ru": "Условия",
        "tr": "Koşullar", "zh-rCN": "条件",
    },
    "Namespace": {
        "ar": "مساحة الأسماء", "de": "Namespace", "es": "Espacio de nombres",
        "fr": "Espace de noms", "hi": "नेमस्पेस", "ja": "名前空間",
        "pt": "Namespace", "ru": "Пространство имён", "tr": "Ad alanı",
        "zh-rCN": "命名空间",
    },
    "Global": {
        "ar": "عام", "de": "Global", "es": "Global", "fr": "Global",
        "hi": "ग्लोबल", "ja": "グローバル", "pt": "Global", "ru": "Глобально",
        "tr": "Global", "zh-rCN": "全局",
    },
    "Mode": {
        "ar": "الوضع", "de": "Modus", "es": "Modo", "fr": "Mode",
        "hi": "मोड", "ja": "モード", "pt": "Modo", "ru": "Режим",
        "tr": "Mod", "zh-rCN": "模式",
    },
    "Navigation": {
        "ar": "التنقل", "de": "Navigation", "es": "Navegación", "fr": "Navigation",
        "hi": "नेविगेशन", "ja": "ナビゲーション", "pt": "Navegação", "ru": "Навигация",
        "tr": "Gezinme", "zh-rCN": "导航",
    },
    "Minimal": {
        "ar": "بسيط", "de": "Minimal", "es": "Mínimo", "fr": "Minimal",
        "hi": "मिनिमल", "ja": "ミニマル", "pt": "Mínimo", "ru": "Минимал",
        "tr": "Minimal", "zh-rCN": "极简",
    },
    "Orange": {
        "ar": "برتقالي", "de": "Orange", "es": "Naranja", "fr": "Orange",
        "hi": "नारंगी", "ja": "オレンジ", "pt": "Laranja", "ru": "Оранжевый",
        "tr": "Turuncu", "zh-rCN": "橙色",
    },
    "Pink": {
        "ar": "وردي", "de": "Pink", "es": "Rosa", "fr": "Rose",
        "hi": "गुलाबी", "ja": "ピンク", "pt": "Rosa", "ru": "Розовый",
        "tr": "Pembe", "zh-rCN": "粉色",
    },
    "Ambient / AOD": {
        "ar": "الشاشة المحيطة / AOD",
    },
    "Ambient & AOD": {
        "ar": "الشاشة المحيطة و AOD",
    },
    "Always-on display & doze": {
        "ar": "العرض الدائم والخمول", "de": "Always-on-Display & Doze",
        "es": "Pantalla siempre activa y doze", "fr": "Écran always-on et doze",
        "hi": "अलवेज़-ऑन डिस्प्ले और doze", "ja": "常時表示とDoze",
        "pt": "Tela sempre ativa e doze", "ru": "Always-on дисплей и doze",
        "tr": "Her zaman açık ekran ve doze", "zh-rCN": "常亮显示和休眠",
    },
    "Evolver batch": {
        "ar": "دفعة Evolver", "de": "Evolver-Stapel", "es": "Lote de Evolver",
        "fr": "Lot Evolver", "hi": "Evolver बैच", "ja": "Evolverバッチ",
        "pt": "Lote Evolver", "ru": "Пакет Evolver", "tr": "Evolver toplu işlemi",
        "zh-rCN": "Evolver 批量",
    },
    "Apply multiple Evolver keys at once": {
        "ar": "تطبيق عدة مفاتيح Evolver مرة واحدة",
        "de": "Mehrere Evolver-Schlüssel gleichzeitig anwenden",
        "es": "Aplicar varias claves de Evolver a la vez",
        "fr": "Appliquer plusieurs clés Evolver à la fois",
        "hi": "एक साथ कई Evolver कुंजियाँ लागू करें",
        "ja": "複数のEvolverキーを一度に適用",
        "pt": "Aplicar várias chaves do Evolver de uma vez",
        "ru": "Применить несколько ключей Evolver сразу",
        "tr": "Birden fazla Evolver anahtarını aynı anda uygula",
        "zh-rCN": "一次应用多个 Evolver 键",
    },
    "Lockscreen": {
        "ar": "شاشة القفل", "de": "Sperrbildschirm", "es": "Pantalla de bloqueo",
        "fr": "Écran de verrouillage", "hi": "लॉकस्क्रीन", "ja": "ロック画面",
        "pt": "Tela de bloqueio", "ru": "Экран блокировки", "tr": "Kilit ekranı",
        "zh-rCN": "锁屏",
    },
    "Clock, shortcuts, weather, UDFPS": {
        "ar": "الساعة، الاختصارات، الطقس، UDFPS",
        "de": "Uhr, Verknüpfungen, Wetter, UDFPS",
        "es": "Reloj, atajos, clima, UDFPS",
        "fr": "Horloge, raccourcis, météo, UDFPS",
        "hi": "घड़ी, शॉर्टकट, मौसम, UDFPS",
        "ja": "時計、ショートカット、天気、UDFPS",
        "pt": "Relógio, atalhos, clima, UDFPS",
        "ru": "Часы, ярлыки, погода, UDFPS",
        "tr": "Saat, kısayollar, hava durumu, UDFPS",
        "zh-rCN": "时钟、快捷方式、天气、UDFPS",
    },
    "Gesture / 3-button / navbar": {
        "ar": "إيماءة / 3 أزرار / شريط التنقل",
        "de": "Geste / 3-Tasten / Navigationsleiste",
        "es": "Gesto / 3 botones / barra de navegación",
        "fr": "Geste / 3 boutons / barre de navigation",
        "hi": "जेस्चर / 3-बटन / नेविगेशन बार",
        "ja": "ジェスチャー / 3ボタン / ナビゲーションバー",
        "pt": "Gesto / 3 botões / barra de navegação",
        "ru": "Жест / 3 кнопки / панель навигации",
        "tr": "Hareket / 3 düğme / gezinme çubuğu",
        "zh-rCN": "手势 / 3 按钮 / 导航栏",
    },
    "Heads-up": {
        "ar": "تنبيه منبثق", "de": "Heads-up", "es": "Heads-up",
        "fr": "Heads-up", "hi": "हेड्स-अप", "ja": "Heads-up",
        "pt": "Heads-up", "ru": "Heads-up", "tr": "Heads-up",
        "zh-rCN": "悬浮通知",
    },
    "Heads-up, less boring, timeout": {
        "ar": "تنبيه منبثق، إزالة الإزعاج، المهلة",
        "de": "Heads-up, less boring, Timeout",
        "es": "Heads-up, less boring, tiempo de espera",
        "fr": "Heads-up, less boring, délai",
        "hi": "हेड्स-अप, less boring, टाइमआउट",
        "ja": "Heads-up、less boring、タイムアウト",
        "pt": "Heads-up, less boring, tempo limite",
        "ru": "Heads-up, less boring, таймаут",
        "tr": "Heads-up, less boring, zaman aşımı",
        "zh-rCN": "Heads-up、less boring、超时",
    },
    "QS Tiles": {
        "ar": "بلاطات QS", "de": "QS-Kacheln", "hi": "QS टाइल्स",
        "ru": "QS-плитки", "tr": "QS Kutucukları",
        "zh-rCN": "QS 图块",
    },
    "Configure Quick Settings tiles & panel": {
        "ar": "تهيئة بلاطات ولوحة الإعدادات السريعة",
        "de": "Schnelleinstellungen-Kacheln & -Panel konfigurieren",
        "es": "Configurar mosaicos y panel de ajustes rápidos",
        "fr": "Configurer les tuiles et le panneau de réglages rapides",
        "hi": "क्विक सेटिंग्स टाइल्स और पैनल कॉन्फ़िगर करें",
        "ja": "クイック設定のタイルとパネルを設定",
        "pt": "Configurar mosaicos e painel de configurações rápidas",
        "ru": "Настроить плитки и панель быстрых настроек",
        "tr": "Hızlı ayar kutucuklarını ve panelini yapılandır",
        "zh-rCN": "配置快速设置图块和面板",
    },
    "Custom Setting": {
        "ar": "إعداد مخصص", "de": "Benutzerdefinierte Einstellung",
        "es": "Ajuste personalizado", "fr": "Paramètre personnalisé",
        "hi": "कस्टम सेटिंग", "ja": "カスタム設定",
        "pt": "Configuração personalizada", "ru": "Своё значение",
        "tr": "Özel ayar", "zh-rCN": "自定义设置",
    },
    "Status bar": {
        "ar": "شريط الحالة", "de": "Statusleiste", "es": "Barra de estado",
        "fr": "Barre d'état", "hi": "स्टेटस बार", "ja": "ステータスバー",
        "pt": "Barra de status", "ru": "Строка состояния", "tr": "Durum çubuğu",
        "zh-rCN": "状态栏",
    },
    "Clock, battery, icons, traffic": {
        "ar": "الساعة، البطارية، الأيقونات، حركة البيانات",
        "de": "Uhr, Akku, Symbole, Traffic",
        "es": "Reloj, batería, iconos, tráfico",
        "fr": "Horloge, batterie, icônes, trafic",
        "hi": "घड़ी, बैटरी, आइकन, ट्रैफिक",
        "ja": "時計、バッテリー、アイコン、トラフィック",
        "pt": "Relógio, bateria, ícones, tráfego",
        "ru": "Часы, батарея, значки, трафик",
        "tr": "Saat, pil, simgeler, trafik",
        "zh-rCN": "时钟、电量、图标、流量",
    },
    "Theme & Monet": {
        "ar": "السمة و Monet", "de": "Design & Monet",
        "es": "Tema y Monet", "fr": "Thème et Monet",
        "hi": "थीम और Monet", "ja": "テーマとMonet",
        "pt": "Tema e Monet", "ru": "Тема и Monet",
        "tr": "Tema ve Monet", "zh-rCN": "主题和 Monet",
    },
    "Accent, Monet, icons, fonts": {
        "ar": "اللون المميز، Monet، الأيقونات، الخطوط",
        "de": "Akzentfarbe, Monet, Symbole, Schriftarten",
        "es": "Acento, Monet, iconos, fuentes",
        "fr": "Accent, Monet, icônes, polices",
        "hi": "एक्सेंट, Monet, आइकन, फ़ॉन्ट",
        "ja": "アクセント、Monet、アイコン、フォント",
        "pt": "Destaque, Monet, ícones, fontes",
        "ru": "Акцент, Monet, значки, шрифты",
        "tr": "Vurgu, Monet, simgeler, yazı tipleri",
        "zh-rCN": "强调色、Monet、图标、字体",
    },
    "Root": {
        "ar": "روت",
    },
    "Android API": {
        "ar": "واجهة Android",
    },
    "ms": {
        "ru": "мс", "zh-rCN": "毫秒",
    },
    "via %1$s": {
        "ar": "عبر %1$s", "de": "über %1$s", "es": "vía %1$s",
        "fr": "via %1$s", "hi": "%1$s के माध्यम से", "ja": "%1$s 経由",
        "pt": "via %1$s", "ru": "через %1$s", "tr": "%1$s üzerinden",
        "zh-rCN": "通过 %1$s",
    },
    "Total": {
        "ar": "الإجمالي", "de": "Gesamt", "hi": "कुल", "ja": "合計",
        "ru": "Всего", "tr": "Toplam", "zh-rCN": "总计",
    },
    "%1$d app(s)": {
        "ar": "%1$d تطبيق", "de": "%1$d App(s)", "hi": "%1$d ऐप",
        "ja": "%1$d 個のアプリ", "ru": "%1$d прил.",
        "tr": "%1$d uygulama", "zh-rCN": "%1$d 个应用",
    },
    "Latitude": {
        "ar": "خط العرض", "de": "Breitengrad", "es": "Latitud",
        "hi": "अक्षांश", "ja": "緯度",
        "pt": "Latitude", "ru": "Широта", "tr": "Enlem",
        "zh-rCN": "纬度",
    },
    "Longitude": {
        "ar": "خط الطول", "de": "Längengrad", "es": "Longitud",
        "hi": "देशांतर", "ja": "経度",
        "pt": "Longitude", "ru": "Долгота", "tr": "Boylam",
        "zh-rCN": "经度",
    },
    "Minute": {
        "ar": "دقيقة", "de": "Minute", "hi": "मिनट", "ja": "分",
        "ru": "Минута", "tr": "Dakika", "zh-rCN": "分钟",
    },
    "Variables": {
        "ar": "المتغيرات", "de": "Variablen", "hi": "वेरिएबल",
        "ja": "変数", "ru": "Переменные", "tr": "Değişkenler",
        "zh-rCN": "变量",
    },
    "Name": {
        "ar": "الاسم", "de": "Name", "es": "Nombre", "fr": "Nom",
        "hi": "नाम", "ja": "名前", "pt": "Nome", "ru": "Имя",
        "tr": "Ad", "zh-rCN": "名称",
    },
    "Actions (%1$d)": {
        "ar": "الإجراءات (%1$d)", "de": "Aktionen (%1$d)", "es": "Acciones (%1$d)",
        "fr": "Actions (%1$d)", "hi": "क्रियाएँ (%1$d)", "ja": "アクション (%1$d)",
        "pt": "Ações (%1$d)", "ru": "Действия (%1$d)", "tr": "Eylemler (%1$d)",
        "zh-rCN": "操作 (%1$d)",
    },
    "Description": {
        "ar": "الوصف", "de": "Beschreibung", "hi": "विवरण",
        "ja": "説明", "ru": "Описание", "tr": "Açıklama",
        "zh-rCN": "描述",
    },
    "Allow local/private network destinations": {
        "ar": "السماح بوجهات الشبكة المحلية/الخاصة",
        "de": "Lokale/private Netzwerkziele erlauben",
        "es": "Permitir destinos de red locales/privados",
        "fr": "Autoriser les destinations réseau locales/privées",
        "hi": "स्थानीय/निजी नेटवर्क गंतव्यों की अनुमति दें",
        "ja": "ローカル/プライベートネットワーク宛先を許可",
        "pt": "Permitir destinos de rede locais/privados",
        "ru": "Разрешить локальные/частные адреса",
        "tr": "Yerel/özel ağ hedeflerine izin ver",
        "zh-rCN": "允许本地/专用网络目标",
    },
    "Base: %1$d ms": {
        "ar": "الأساس: %1$d ms", "de": "Basis: %1$d ms", "es": "Base: %1$d ms",
        "fr": "Base : %1$d ms", "hi": "बेस: %1$d ms", "ja": "ベース: %1$d ms",
        "pt": "Base: %1$d ms", "ru": "База: %1$d мс", "tr": "Temel: %1$d ms",
        "zh-rCN": "基准：%1$d ms",
    },
    "Custom key (name or code)": {
        "ar": "مفتاح مخصص (اسم أو رمز)",
        "de": "Eigene Taste (Name oder Code)",
        "es": "Tecla personalizada (nombre o código)",
        "fr": "Touche personnalisée (nom ou code)",
        "hi": "कस्टम कुंजी (नाम या कोड)",
        "ja": "カスタムキー（名前またはコード）",
        "pt": "Tecla personalizada (nome ou código)",
        "ru": "Своя клавиша (имя или код)",
        "tr": "Özel tuş (ad veya kod)",
        "zh-rCN": "自定义按键（名称或代码）",
    },
    "Degrees Celsius, e.g. 40": {
        "ar": "درجة مئوية، مثال: 40",
        "de": "Grad Celsius, z. B. 40",
        "es": "Grados Celsius, p. ej. 40",
        "fr": "Degrés Celsius, p. ex. 40",
        "hi": "डिग्री सेल्सियस, जैसे 40",
        "ja": "摂氏（例: 40）",
        "pt": "Graus Celsius, ex. 40",
        "ru": "Градусы Цельсия, напр. 40",
        "tr": "Santigrat derece, örn. 40",
        "zh-rCN": "摄氏度，例如 40",
    },
    "SIM %1$d": {
        "ar": "شريحة %1$d",
    },
    "%1$d min": {
        "ar": "%1$d دقيقة", "de": "%1$d Min.", "hi": "%1$d मिनट",
        "ja": "%1$d分", "ru": "%1$d мин", "tr": "%1$d dk",
        "zh-rCN": "%1$d 分钟",
    },
    "1 min": {
        "ar": "دقيقة واحدة", "de": "1 Min.", "hi": "1 मिनट",
        "ja": "1分", "ru": "1 мин", "tr": "1 dk", "zh-rCN": "1 分钟",
    },
    "5 min": {
        "ar": "5 دقائق", "de": "5 Min.", "hi": "5 मिनट",
        "ja": "5分", "ru": "5 мин", "tr": "5 dk", "zh-rCN": "5 分钟",
    },
    "10 min": {
        "ar": "10 دقائق", "de": "10 Min.", "hi": "10 मिनट",
        "ja": "10分", "ru": "10 мин", "tr": "10 dk", "zh-rCN": "10 分钟",
    },
    "Radius: %1$d m": {
        "ar": "نصف القطر: %1$d م", "de": "Radius: %1$d m", "es": "Radio: %1$d m",
        "fr": "Rayon : %1$d m", "hi": "त्रिज्या: %1$d मी", "ja": "半径: %1$d m",
        "pt": "Raio: %1$d m", "ru": "Радиус: %1$d м", "tr": "Yarıçap: %1$d m",
        "zh-rCN": "半径：%1$d 米",
    },
    "At least": {
        "ar": "على الأقل", "de": "Mindestens", "es": "Al menos",
        "fr": "Au moins", "hi": "कम से कम", "ja": "以上",
        "pt": "No mínimo", "ru": "Не менее", "tr": "En az",
        "zh-rCN": "至少",
    },
    "At most": {
        "ar": "على الأكثر", "de": "Höchstens", "es": "Como máximo",
        "fr": "Au plus", "hi": "अधिक से अधिक", "ja": "以下",
        "pt": "No máximo", "ru": "Не более", "tr": "En çok",
        "zh-rCN": "至多",
    },
    "Between (inclusive)": {
        "ar": "بين (شامل)", "de": "Zwischen (einschließlich)",
        "es": "Entre (incluido)", "fr": "Entre (inclus)",
        "hi": "के बीच (समावेशी)", "ja": "間（範囲内）",
        "pt": "Entre (inclusive)", "ru": "Между (включительно)",
        "tr": "Arasında (dahil)", "zh-rCN": "介于（含边界）",
    },
    "The upper bound must be greater than or equal to the lower bound.": {
        "ar": "يجب أن يكون الحد الأعلى أكبر من أو يساوي الحد الأدنى.",
        "de": "Die Obergrenze muss größer oder gleich der Untergrenze sein.",
        "es": "El límite superior debe ser mayor o igual que el inferior.",
        "fr": "La borne supérieure doit être supérieure ou égale à la borne inférieure.",
        "hi": "ऊपरी सीमा निचली सीमा से बड़ी या बराबर होनी चाहिए।",
        "ja": "上限は下限以上である必要があります。",
        "pt": "O limite superior deve ser maior ou igual ao inferior.",
        "ru": "Верхняя граница должна быть не меньше нижней.",
        "tr": "Üst sınır alt sınırdan büyük veya eşit olmalıdır.",
        "zh-rCN": "上限必须大于或等于下限。",
    },
    "Enter a finite number.": {
        "ar": "أدخل رقمًا محدودًا.", "de": "Gib eine endliche Zahl ein.",
        "es": "Introduce un número finito.", "fr": "Saisissez un nombre fini.",
        "hi": "एक परिमित संख्या दर्ज करें।", "ja": "有限の数値を入力してください。",
        "pt": "Insira um número finito.", "ru": "Введите конечное число.",
        "tr": "Sonlu bir sayı girin.", "zh-rCN": "请输入有限数字。",
    },
    "Linear acceleration magnitude (m/s²)": {
        "ar": "مقدار التسارع الخطي (م/ث²)", "de": "Lineare Beschleunigung (m/s²)",
        "es": "Magnitud de aceleración lineal (m/s²)",
        "fr": "Amplitude d'accélération linéaire (m/s²)",
        "hi": "रैखिक त्वरण परिमाण (m/s²)", "ja": "線形加速度の大きさ (m/s²)",
        "pt": "Magnitude da aceleração linear (m/s²)",
        "ru": "Модуль линейного ускорения (м/с²)", "tr": "Doğrusal ivme büyüklüğü (m/s²)",
        "zh-rCN": "线性加速度大小 (m/s²)",
    },
    "Gravity magnitude (m/s²)": {
        "ar": "مقدار الجاذبية (م/ث²)", "de": "Schwerebeschleunigung (m/s²)",
        "es": "Magnitud de gravedad (m/s²)", "fr": "Amplitude de gravité (m/s²)",
        "hi": "गुरुत्व परिमाण (m/s²)", "ja": "重力の大きさ (m/s²)",
        "pt": "Magnitude da gravidade (m/s²)", "ru": "Модуль гравитации (м/с²)",
        "tr": "Yerçekimi büyüklüğü (m/s²)", "zh-rCN": "重力大小 (m/s²)",
    },
    "Angular velocity magnitude (rad/s)": {
        "ar": "مقدار السرعة الزاوية (راد/ث)", "de": "Winkelgeschwindigkeit (rad/s)",
        "es": "Magnitud de velocidad angular (rad/s)",
        "fr": "Amplitude de vitesse angulaire (rad/s)",
        "hi": "कोणीय वेग परिमाण (rad/s)", "ja": "角速度の大きさ (rad/s)",
        "pt": "Magnitude da velocidade angular (rad/s)",
        "ru": "Модуль угловой скорости (рад/с)", "tr": "Açısal hız büyüklüğü (rad/s)",
        "zh-rCN": "角速度大小 (rad/s)",
    },
    "Requires the physical sensor. Vector readings use magnitude. A matching condition remains active until it no longer matches.": {
        "ar": "يتطلب المستشعر الفعلي. قراءات المتجه تستخدم المقدار. يبقى الشرط المطابق نشطًا حتى يتوقف عن المطابقة.",
        "de": "Erfordert den physischen Sensor. Vektorwerte nutzen die Magnitude. Eine passende Bedingung bleibt aktiv, bis sie nicht mehr passt.",
        "es": "Requiere el sensor físico. Las lecturas vectoriales usan la magnitud. Una condición coincidente permanece activa hasta que deje de coincidir.",
        "fr": "Nécessite le capteur physique. Les lectures vectorielles utilisent l'amplitude. Une condition correspondante reste active tant qu'elle correspond.",
        "hi": "भौतिक सेंसर आवश्यक है। वेक्टर रीडिंग परिमाण का उपयोग करती हैं। मिलती-जुलती शर्त तब तक सक्रिय रहती है जब तक वह मेल न खाए।",
        "ja": "物理センサーが必要です。ベクトル値は大きさを使用します。一致する条件は一致しなくなるまでアクティブです。",
        "pt": "Requer o sensor físico. Leituras vetoriais usam a magnitude. Uma condição correspondente permanece ativa até deixar de corresponder.",
        "ru": "Требуется физический датчик. Векторные показания — по модулю. Подходящее условие активно, пока совпадает.",
        "tr": "Fiziksel sensör gerekir. Vektör okumaları büyüklük kullanır. Eşleşen koşul, eşleşme bitene kadar etkin kalır.",
        "zh-rCN": "需要物理传感器。矢量读数使用大小。匹配的条件在不再匹配之前保持活动。",
    },
    "Hinge angle (°)": {
        "ar": "زاوية المفصلة (°)", "de": "Scharnierwinkel (°)",
        "es": "Ángulo de bisagra (°)", "fr": "Angle de charnière (°)",
        "hi": "हिंज कोण (°)", "ja": "ヒンジ角度 (°)",
        "pt": "Ângulo da dobradiça (°)", "ru": "Угол шарнира (°)",
        "tr": "Menteşe açısı (°)", "zh-rCN": "铰链角度 (°)",
    },
    "Relative humidity (%)": {
        "ar": "الرطوبة النسبية (%)", "de": "Relative Luftfeuchtigkeit (%)",
        "es": "Humedad relativa (%)", "fr": "Humidité relative (%)",
        "hi": "सापेक्ष आर्द्रता (%)", "ja": "相対湿度 (%)",
        "pt": "Umidade relativa (%)", "ru": "Относительная влажность (%)",
        "tr": "Bağıl nem (%)", "zh-rCN": "相对湿度 (%)",
    },
    "Magnetic field magnitude (µT)": {
        "ar": "مقدار المجال المغناطيسي (µT)", "de": "Magnetfeldstärke (µT)",
        "es": "Magnitud del campo magnético (µT)",
        "fr": "Amplitude du champ magnétique (µT)",
        "hi": "चुंबकीय क्षेत्र परिमाण (µT)", "ja": "磁場の大きさ (µT)",
        "pt": "Magnitude do campo magnético (µT)",
        "ru": "Модуль магнитного поля (мкТл)", "tr": "Manyetik alan büyüklüğü (µT)",
        "zh-rCN": "磁场大小 (µT)",
    },
    "Pressure (hPa)": {
        "ar": "الضغط (hPa)", "de": "Druck (hPa)", "es": "Presión (hPa)",
        "fr": "Pression (hPa)", "hi": "दबाव (hPa)", "ja": "気圧 (hPa)",
        "pt": "Pressão (hPa)", "ru": "Давление (гПа)", "tr": "Basınç (hPa)",
        "zh-rCN": "气压 (hPa)",
    },
    "Ambient temperature (°C)": {
        "ar": "درجة حرارة المحيط (°C)", "de": "Umgebungstemperatur (°C)",
        "es": "Temperatura ambiente (°C)", "fr": "Température ambiante (°C)",
        "hi": "परिवेश का तापमान (°C)", "ja": "周囲温度 (°C)",
        "pt": "Temperatura ambiente (°C)", "ru": "Температура воздуха (°C)",
        "tr": "Ortam sıcaklığı (°C)", "zh-rCN": "环境温度 (°C)",
    },
    "Threshold / lower bound (%1$s)": {
        "ar": "الحد / الحد الأدنى (%1$s)", "de": "Schwelle / Untergrenze (%1$s)",
        "es": "Umbral / límite inferior (%1$s)", "fr": "Seuil / borne inférieure (%1$s)",
        "hi": "थ्रेशोल्ड / निचली सीमा (%1$s)", "ja": "しきい値 / 下限 (%1$s)",
        "pt": "Limiar / limite inferior (%1$s)", "ru": "Порог / нижняя граница (%1$s)",
        "tr": "Eşik / alt sınır (%1$s)", "zh-rCN": "阈值 / 下限 (%1$s)",
    },
    "Upper bound (%1$s)": {
        "ar": "الحد الأعلى (%1$s)", "de": "Obergrenze (%1$s)",
        "es": "Límite superior (%1$s)", "fr": "Borne supérieure (%1$s)",
        "hi": "ऊपरी सीमा (%1$s)", "ja": "上限 (%1$s)",
        "pt": "Limite superior (%1$s)", "ru": "Верхняя граница (%1$s)",
        "tr": "Üst sınır (%1$s)", "zh-rCN": "上限 (%1$s)",
    },
    "This device does not expose the selected sensor. This trigger cannot run here.": {
        "ar": "هذا الجهاز لا يوفر المستشعر المحدد. لا يمكن لهذا المشغل العمل هنا.",
        "de": "Dieses Gerät stellt den ausgewählten Sensor nicht bereit. Dieser Auslöser kann hier nicht laufen.",
        "es": "Este dispositivo no expone el sensor seleccionado. Este iniciador no puede ejecutarse aquí.",
        "fr": "Cet appareil n'expose pas le capteur sélectionné. Ce déclencheur ne peut pas fonctionner ici.",
        "hi": "यह डिवाइस चयनित सेंसर प्रदान नहीं करता। यह ट्रिगर यहाँ नहीं चल सकता।",
        "ja": "このデバイスには選択されたセンサーがありません。このトリガーはここでは実行できません。",
        "pt": "Este dispositivo não expõe o sensor selecionado. Este gatilho não pode ser executado aqui.",
        "ru": "Это устройство не предоставляет выбранный датчик. Этот триггер здесь не может работать.",
        "tr": "Bu cihaz seçilen sensörü sunmuyor. Bu tetikleyici burada çalışamaz.",
        "zh-rCN": "此设备不提供所选传感器。此触发器无法在此运行。",
    },
    "Array transform": {
        "ar": "تحويل المصفوفات", "de": "Array-Transformation", "es": "Transformación de arrays",
        "fr": "Transformation de tableaux", "hi": "ऐरे ट्रांसफ़ॉर्म", "ja": "配列変換",
        "pt": "Transformação de arrays", "ru": "Преобразование массивов", "tr": "Dizi dönüşümü",
        "zh-rCN": "数组变换",
    },
    "Order, reverse, join and deduplicate JSON arrays": {
        "ar": "ترتيب وقلب ودمج وإزالة تكرار مصفوفات JSON",
        "de": "JSON-Arrays sortieren, umkehren, verbinden und deduplizieren",
        "es": "Ordenar, invertir, unir y deduplicar arrays JSON",
        "fr": "Trier, inverser, joindre et dédupliquer des tableaux JSON",
        "hi": "JSON ऐरे को क्रमित, उलटा, जोड़ें और डुप्लिकेट हटाएँ",
        "ja": "JSON配列の並べ替え・反転・結合・重複削除",
        "pt": "Ordenar, inverter, unir e desduplicar arrays JSON",
        "ru": "Сортировка, реверс, объединение и дедупликация JSON-массивов",
        "tr": "JSON dizilerini sırala, ters çevir, birleştir ve tekilleştir",
        "zh-rCN": "排序、反转、连接和去重 JSON 数组",
    },
    "Date and time": {
        "ar": "التاريخ والوقت", "de": "Datum und Uhrzeit", "es": "Fecha y hora",
        "fr": "Date et heure", "hi": "तारीख और समय", "ja": "日付と時刻",
        "pt": "Data e hora", "ru": "Дата и время", "tr": "Tarih ve saat",
        "zh-rCN": "日期和时间",
    },
    "Parse ISO instants and format in a chosen time zone": {
        "ar": "تحليل اللحظات ISO والتنسيق بمنطقة زمنية مختارة",
        "de": "ISO-Zeitpunkte parsen und in einer Zeitzone formatieren",
        "es": "Analizar instantes ISO y formatear en una zona horaria elegida",
        "fr": "Analyser des instants ISO et formater dans un fuseau choisi",
        "hi": "ISO इंस्टेंट पार्स करें और चुने हुए टाइम ज़ोन में फ़ॉर्मेट करें",
        "ja": "ISO時刻を解析し選択したタイムゾーンで書式設定",
        "pt": "Analisar instantes ISO e formatar em um fuso escolhido",
        "ru": "Разбор ISO-моментов и форматирование в выбранном поясе",
        "tr": "ISO anlarını ayrıştır ve seçilen saat diliminde biçimlendir",
        "zh-rCN": "解析 ISO 时刻并按所选时区格式化",
    },
    "Text encoding": {
        "ar": "ترميز النص", "de": "Textkodierung", "es": "Codificación de texto",
        "fr": "Encodage du texte", "hi": "टेक्स्ट एनकोडिंग", "ja": "テキストエンコーディング",
        "pt": "Codificação de texto", "ru": "Кодирование текста", "tr": "Metin kodlama",
        "zh-rCN": "文本编码",
    },
    "Base64, URL and hexadecimal encoding": {
        "ar": "ترميز Base64 و URL وست عشري",
        "de": "Base64-, URL- und Hexadezimalkodierung",
        "es": "Codificación Base64, URL y hexadecimal",
        "fr": "Encodage Base64, URL et hexadécimal",
        "hi": "Base64, URL और हेक्साडेसिमल एनकोडिंग",
        "ja": "Base64、URL、16進エンコーディング",
        "pt": "Codificação Base64, URL e hexadecimal",
        "ru": "Кодирование Base64, URL и шестнадцатеричное",
        "tr": "Base64, URL ve onaltılık kodlama",
        "zh-rCN": "Base64、URL 和十六进制编码",
    },
    "Cryptographic hash": {
        "ar": "تجزئة تشفيرية", "de": "Kryptografischer Hash",
        "es": "Hash criptográfico", "fr": "Hachage cryptographique",
        "hi": "क्रिप्टोग्राफ़िक हैश", "ja": "暗号学的ハッシュ",
        "pt": "Hash criptográfico", "ru": "Криптографический хеш",
        "tr": "Kriptografik özet", "zh-rCN": "加密哈希",
    },
    "Compute SHA-256 or SHA-512": {
        "ar": "حساب SHA-256 أو SHA-512", "de": "SHA-256 oder SHA-512 berechnen",
        "es": "Calcular SHA-256 o SHA-512", "fr": "Calculer SHA-256 ou SHA-512",
        "hi": "SHA-256 या SHA-512 गणना करें", "ja": "SHA-256 または SHA-512 を計算",
        "pt": "Calcular SHA-256 ou SHA-512", "ru": "Вычислить SHA-256 или SHA-512",
        "tr": "SHA-256 veya SHA-512 hesapla", "zh-rCN": "计算 SHA-256 或 SHA-512",
    },
    "JSON transform": {
        "ar": "تحويل JSON", "de": "JSON-Transformation", "es": "Transformación JSON",
        "fr": "Transformation JSON", "hi": "JSON ट्रांसफ़ॉर्म", "ja": "JSON変換",
        "pt": "Transformação JSON", "ru": "Преобразование JSON", "tr": "JSON dönüşümü",
        "zh-rCN": "JSON 变换",
    },
    "Read JSON Pointer paths, keys and formatted JSON": {
        "ar": "قراءة مسارات JSON Pointer والمفاتيح و JSON منسق",
        "de": "JSON-Pointer-Pfade, Schlüssel und formatiertes JSON lesen",
        "es": "Leer rutas JSON Pointer, claves y JSON formateado",
        "fr": "Lire les chemins JSON Pointer, les clés et le JSON formaté",
        "hi": "JSON पॉइंटर पथ, कुंजियाँ और फ़ॉर्मेटेड JSON पढ़ें",
        "ja": "JSON Pointerのパス、キー、整形済みJSONを読み取り",
        "pt": "Ler caminhos JSON Pointer, chaves e JSON formatado",
        "ru": "Чтение путей JSON Pointer, ключей и форматированного JSON",
        "tr": "JSON Pointer yollarını, anahtarları ve biçimli JSON'u oku",
        "zh-rCN": "读取 JSON Pointer 路径、键和格式化 JSON",
    },
    "Decimal arithmetic": {
        "ar": "حساب عشري", "de": "Dezimalarithmetik", "es": "Aritmética decimal",
        "fr": "Arithmétique décimale", "hi": "दशमलव अंकगणित", "ja": "10進演算",
        "pt": "Aritmética decimal", "ru": "Десятичная арифметика", "tr": "Ondalık aritmetik",
        "zh-rCN": "十进制运算",
    },
    "Calculate with bounded decimal precision": {
        "ar": "الحساب بدقة عشرية محدودة",
        "de": "Rechnen mit begrenzter Dezimalgenauigkeit",
        "es": "Calcular con precisión decimal acotada",
        "fr": "Calculer avec une précision décimale bornée",
        "hi": "सीमित दशमलव परिशुद्धता के साथ गणना",
        "ja": "有限の小数精度で計算",
        "pt": "Calcular com precisão decimal limitada",
        "ru": "Вычисления с ограниченной десятичной точностью",
        "tr": "Sınırlı ondalık hassasiyetle hesapla",
        "zh-rCN": "以有界的小数精度计算",
    },
    "Random value": {
        "ar": "قيمة عشوائية", "de": "Zufallswert", "es": "Valor aleatorio",
        "fr": "Valeur aléatoire", "hi": "यादृच्छिक मान", "ja": "ランダム値",
        "pt": "Valor aleatório", "ru": "Случайное значение", "tr": "Rastgele değer",
        "zh-rCN": "随机值",
    },
    "Generate a UUID, secure token or bounded integer": {
        "ar": "إنشاء UUID أو رمز آمن أو عدد صحيح محدود",
        "de": "UUID, sicheres Token oder begrenzte Ganzzahl erzeugen",
        "es": "Generar UUID, token seguro o entero acotado",
        "fr": "Générer un UUID, un jeton sécurisé ou un entier borné",
        "hi": "UUID, सुरक्षित टोकन या सीमित पूर्णांक जनरेट करें",
        "ja": "UUID、セキュアトークン、範囲内整数を生成",
        "pt": "Gerar UUID, token seguro ou inteiro limitado",
        "ru": "Создать UUID, безопасный токен или целое число в границах",
        "tr": "UUID, güvenli belirteç veya sınırlı tam sayı üret",
        "zh-rCN": "生成 UUID、安全令牌或有界整数",
    },
    "Text transform": {
        "ar": "تحويل النص", "de": "Texttransformation", "es": "Transformación de texto",
        "fr": "Transformation de texte", "hi": "टेक्स्ट ट्रांसफ़ॉर्म", "ja": "テキスト変換",
        "pt": "Transformação de texto", "ru": "Преобразование текста", "tr": "Metin dönüşümü",
        "zh-rCN": "文本变换",
    },
    "Trim, case, replace, split and Unicode substrings": {
        "ar": "تشذيب وحالة واستبدال وتقسيم وسلاسل Unicode فرعية",
        "de": "Trimmen, Groß-/Kleinschreibung, Ersetzen, Aufteilen und Unicode-Teilstrings",
        "es": "Recortar, mayúsculas/minúsculas, reemplazar, dividir y subcadenas Unicode",
        "fr": "Rognage, casse, remplacement, division et sous-chaînes Unicode",
        "hi": "ट्रिम, केस, बदलें, विभाजित करें और यूनिकोड सबस्ट्रिंग",
        "ja": "トリム、大文字小文字、置換、分割、Unicode部分文字列",
        "pt": "Aparar, caixa, substituir, dividir e substrings Unicode",
        "ru": "Обрезка, регистр, замена, разбиение и подстроки Unicode",
        "tr": "Kırpma, büyük/küçük harf, değiştirme, bölme ve Unicode alt dizeleri",
        "zh-rCN": "修剪、大小写、替换、拆分和 Unicode 子字符串",
    },
    "Literal input": {
        "ar": "إدخال حرفي", "de": "Literal-Eingabe", "es": "Entrada literal",
        "fr": "Entrée littérale", "hi": "लिटरल इनपुट", "ja": "リテラル入力",
        "pt": "Entrada literal", "ru": "Литеральный ввод", "tr": "Değişmez girdi",
        "zh-rCN": "字面输入",
    },
    "Input context path (optional)": {
        "ar": "مسار سياق الإدخال (اختياري)", "de": "Eingabekontextpfad (optional)",
        "es": "Ruta de contexto de entrada (opcional)",
        "fr": "Chemin de contexte d'entrée (facultatif)",
        "hi": "इनपुट संदर्भ पथ (वैकल्पिक)", "ja": "入力コンテキストパス（任意）",
        "pt": "Caminho de contexto de entrada (opcional)",
        "ru": "Путь контекста ввода (необязательно)", "tr": "Girdi bağlam yolu (isteğe bağlı)",
        "zh-rCN": "输入上下文路径（可选）",
    },
    "Output context path": {
        "ar": "مسار سياق الإخراج", "de": "Ausgabekontextpfad",
        "es": "Ruta de contexto de salida", "fr": "Chemin de contexte de sortie",
        "hi": "आउटपुट संदर्भ पथ", "ja": "出力コンテキストパス",
        "pt": "Caminho de contexto de saída", "ru": "Путь контекста вывода",
        "tr": "Çıktı bağlam yolu", "zh-rCN": "输出上下文路径",
    },
    "Argument / delimiter / pointer": {
        "ar": "وسيط / فاصل / مؤشر", "de": "Argument / Trennzeichen / Zeiger",
        "es": "Argumento / delimitador / puntero",
        "fr": "Argument / délimiteur / pointeur",
        "hi": "तर्क / विभाजक / पॉइंटर", "ja": "引数 / 区切り / ポインタ",
        "pt": "Argumento / delimitador / ponteiro",
        "ru": "Аргумент / разделитель / указатель", "tr": "Bağımsız / ayraç / işaretçi",
        "zh-rCN": "参数 / 分隔符 / 指针",
    },
    "Replacement text": {
        "ar": "نص الاستبدال", "de": "Ersetzungstext", "es": "Texto de reemplazo",
        "fr": "Texte de remplacement", "hi": "प्रतिस्थापन पाठ", "ja": "置換テキスト",
        "pt": "Texto de substituição", "ru": "Текст замены", "tr": "Değiştirme metni",
        "zh-rCN": "替换文本",
    },
    "Start code point (inclusive)": {
        "ar": "رمز البداية (شامل)", "de": "Start-Codepunkt (einschließlich)",
        "es": "Punto de código inicial (incluido)",
        "fr": "Point de code de départ (inclus)",
        "hi": "प्रारंभ कोड पॉइंट (समावेशी)", "ja": "開始コードポイント（含む）",
        "pt": "Ponto de código inicial (inclusive)",
        "ru": "Начальная кодовая точка (включительно)",
        "tr": "Başlangıç kod noktası (dahil)", "zh-rCN": "起始码点（含）",
    },
    "End code point (exclusive)": {
        "ar": "رمز النهاية (حصري)", "de": "End-Codepunkt (ausschließlich)",
        "es": "Punto de código final (excluido)",
        "fr": "Point de code de fin (exclu)",
        "hi": "अंतिम कोड पॉइंट (अनन्य)", "ja": "終了コードポイント（含まない）",
        "pt": "Ponto de código final (exclusivo)",
        "ru": "Конечная кодовая точка (исключая)",
        "tr": "Bitiş kod noktası (hariç)", "zh-rCN": "结束码点（不含）",
    },
    "Results are available to later actions in this run. Input path overrides literal input. JSON uses RFC 6901 pointers. Dates use ISO-8601 instants. Arguments and results are bounded; invalid settings fail explicitly.": {
        "ar": "النتائج متاحة للإجراءات اللاحقة في هذا التشغيل. مسار الإدخال يتجاوز الإدخال الحرفي. JSON يستخدم مؤشرات RFC 6901. التواريخ لحظات ISO-8601. الوسائط والنتائج محدودة؛ الإعدادات غير الصالحة تفشل صراحةً.",
        "de": "Ergebnisse stehen späteren Aktionen in diesem Lauf zur Verfügung. Der Eingabepfad überschreibt die wörtliche Eingabe. JSON verwendet RFC-6901-Zeiger. Daten sind ISO-8601-Zeitpunkte. Argumente und Ergebnisse sind begrenzt; ungültige Einstellungen schlagen explizit fehl.",
        "es": "Los resultados están disponibles para acciones posteriores en esta ejecución. La ruta de entrada anula la entrada literal. JSON usa punteros RFC 6901. Las fechas son instantes ISO-8601. Argumentos y resultados acotados; los ajustes no válidos fallan explícitamente.",
        "fr": "Les résultats sont disponibles pour les actions suivantes de cette exécution. Le chemin d'entrée prime sur l'entrée littérale. JSON utilise des pointeurs RFC 6901. Les dates sont des instants ISO-8601. Arguments et résultats bornés ; les réglages invalides échouent explicitement.",
        "hi": "परिणाम इस रन में बाद की क्रियाओं के लिए उपलब्ध हैं। इनपुट पथ लिटरल इनपुट को ओवरराइड करता है। JSON RFC 6901 पॉइंटर का उपयोग करता है। तिथियाँ ISO-8601 इंस्टेंट हैं। तर्क और परिणाम सीमित हैं; अमान्य सेटिंग स्पष्ट रूप से विफल होती हैं।",
        "ja": "結果はこの実行内の後続アクションで利用可能です。入力パスはリテラル入力を上書きします。JSONはRFC 6901ポインターを使用します。日付はISO-8601インスタントです。引数と結果には上限があり、無効な設定は明示的に失敗します。",
        "pt": "Os resultados estão disponíveis para ações posteriores nesta execução. O caminho de entrada substitui a entrada literal. JSON usa ponteiros RFC 6901. Datas são instantes ISO-8601. Argumentos e resultados são limitados; configurações inválidas falham explicitamente.",
        "ru": "Результаты доступны последующим действиям в этом запуске. Путь ввода переопределяет литеральный ввод. JSON использует указатели RFC 6901. Даты — моменты ISO-8601. Аргументы и результаты ограничены; недопустимые настройки завершаются явной ошибкой.",
        "tr": "Sonuçlar bu çalıştırmadaki sonraki eylemler için kullanılabilir. Girdi yolu, değişmez girdiyi geçersiz kılar. JSON, RFC 6901 işaretçilerini kullanır. Tarihler ISO-8601 anlarıdır. Bağımsız değişkenler ve sonuçlar sınırlıdır; geçersiz ayarlar açıkça başarısız olur.",
        "zh-rCN": "结果可供本次运行中的后续操作使用。输入路径会覆盖字面输入。JSON 使用 RFC 6901 指针。日期为 ISO-8601 时刻。参数和结果有界；无效设置会显式失败。",
    },
    "Date pattern (default: uuuu-MM-dd HH:mm:ss)": {
        "ar": "نمط التاريخ (الافتراضي: uuuu-MM-dd HH:mm:ss)",
        "de": "Datumsmuster (Standard: uuuu-MM-dd HH:mm:ss)",
        "es": "Patrón de fecha (predeterminado: uuuu-MM-dd HH:mm:ss)",
        "fr": "Motif de date (par défaut : uuuu-MM-dd HH:mm:ss)",
        "hi": "तिथि पैटर्न (डिफ़ॉल्ट: uuuu-MM-dd HH:mm:ss)",
        "ja": "日付パターン（デフォルト: uuuu-MM-dd HH:mm:ss）",
        "pt": "Padrão de data (padrão: uuuu-MM-dd HH:mm:ss)",
        "ru": "Шаблон даты (по умолчанию: uuuu-MM-dd HH:mm:ss)",
        "tr": "Tarih deseni (varsayılan: uuuu-MM-dd HH:mm:ss)",
        "zh-rCN": "日期模式（默认：uuuu-MM-dd HH:mm:ss）",
    },
    "Time zone (default: UTC)": {
        "ar": "المنطقة الزمنية (الافتراضي: UTC)",
        "de": "Zeitzone (Standard: UTC)",
        "es": "Zona horaria (predeterminada: UTC)",
        "fr": "Fuseau horaire (par défaut : UTC)",
        "hi": "टाइम ज़ोन (डिफ़ॉल्ट: UTC)",
        "ja": "タイムゾーン（デフォルト: UTC）",
        "pt": "Fuso horário (padrão: UTC)",
        "ru": "Часовой пояс (по умолчанию: UTC)",
        "tr": "Saat dilimi (varsayılan: UTC)",
        "zh-rCN": "时区（默认：UTC）",
    },
    "Maximum integer (inclusive)": {
        "ar": "أقصى عدد صحيح (شامل)", "de": "Maximale Ganzzahl (einschließlich)",
        "es": "Entero máximo (incluido)", "fr": "Entier maximum (inclus)",
        "hi": "अधिकतम पूर्णांक (समावेशी)", "ja": "最大整数（含む）",
        "pt": "Inteiro máximo (inclusive)", "ru": "Максимальное целое (включительно)",
        "tr": "Maksimum tam sayı (dahil)", "zh-rCN": "最大整数（含）",
    },
    "Minimum integer (inclusive)": {
        "ar": "أدنى عدد صحيح (شامل)", "de": "Minimale Ganzzahl (einschließlich)",
        "es": "Entero mínimo (incluido)", "fr": "Entier minimum (inclus)",
        "hi": "न्यूनतम पूर्णांक (समावेशी)", "ja": "最小整数（含む）",
        "pt": "Inteiro mínimo (inclusive)", "ru": "Минимальное целое (включительно)",
        "tr": "Minimum tam sayı (dahil)", "zh-rCN": "最小整数（含）",
    },
    "Maximum: %1$d%%": {
        "ar": "الحد الأقصى: %1$d%%", "de": "Maximum: %1$d%%", "es": "Máximo: %1$d%%",
        "fr": "Maximum : %1$d%%", "hi": "अधिकतम: %1$d%%", "ja": "最大: %1$d%%",
        "pt": "Máximo: %1$d%%", "ru": "Максимум: %1$d%%", "tr": "En fazla: %1$d%%",
        "zh-rCN": "最大：%1$d%%",
    },
    "Starts at %1$d%%": {
        "ar": "يبدأ عند %1$d%%", "de": "Beginnt bei %1$d%%", "es": "Comienza al %1$d%%",
        "fr": "Commence à %1$d%%", "hi": "%1$d%% पर शुरू", "ja": "%1$d%% で開始",
        "pt": "Inicia em %1$d%%", "ru": "Начинается с %1$d%%", "tr": "%1$d%%'de başlar",
        "zh-rCN": "在 %1$d%% 开始",
    },
    "Request headers (one Name: value per line)": {
        "ar": "ترويسات الطلب (الاسم: القيمة في كل سطر)",
        "de": "Request-Header (ein Name: Wert pro Zeile)",
        "es": "Encabezados de solicitud (un Nombre: valor por línea)",
        "fr": "En-têtes de requête (un Nom : valeur par ligne)",
        "hi": "अनुरोध हेडर (प्रति पंक्ति एक नाम: मान)",
        "ja": "リクエストヘッダー（1行に名前: 値）",
        "pt": "Cabeçalhos de solicitação (um Nome: valor por linha)",
        "ru": "Заголовки запроса (имя: значение в каждой строке)",
        "tr": "İstek başlıkları (her satıra bir Ad: değer)",
        "zh-rCN": "请求头（每行一个名称: 值）",
    },
    "Up to 32 headers and 8 KiB. Set Content-Type or Authorization here. Custom headers are removed on redirects to another origin. Transport framing headers cannot be overridden.": {
        "ar": "حتى 32 ترويسة و 8 KiB. عيّن Content-Type أو Authorization هنا. تُزال الترويسات المخصصة عند إعادة التوجيه إلى أصل آخر. لا يمكن تجاوز ترويسات الإطار النقلي.",
        "de": "Bis zu 32 Header und 8 KiB. Content-Type oder Authorization hier setzen. Eigene Header werden bei Weiterleitungen zu anderer Herkunft entfernt. Transport-Frame-Header können nicht überschrieben werden.",
        "es": "Hasta 32 encabezados y 8 KiB. Define Content-Type o Authorization aquí. Los encabezados personalizados se eliminan en redirecciones a otro origen. Los encabezados de enmarcado de transporte no se pueden sobrescribir.",
        "fr": "Jusqu'à 32 en-têtes et 8 KiB. Définissez Content-Type ou Authorization ici. Les en-têtes personnalisés sont supprimés lors des redirections vers une autre origine. Les en-têtes de trame de transport ne peuvent pas être remplacés.",
        "hi": "32 हेडर और 8 KiB तक। Content-Type या Authorization यहाँ सेट करें। दूसरे मूल पर रीडायरेक्ट पर कस्टम हेडर हटा दिए जाते हैं। ट्रांसपोर्ट फ्रेमिंग हेडर ओवरराइड नहीं किए जा सकते।",
        "ja": "最大32ヘッダー・8KiB。ここでContent-TypeやAuthorizationを設定します。別オリジンへのリダイレクトではカスタムヘッダーは削除されます。転送フレーミングヘッダーは上書きできません。",
        "pt": "Até 32 cabeçalhos e 8 KiB. Defina Content-Type ou Authorization aqui. Cabeçalhos personalizados são removidos em redirecionamentos para outra origem. Cabeçalhos de enquadramento de transporte não podem ser substituídos.",
        "ru": "До 32 заголовков и 8 КиБ. Задайте Content-Type или Authorization здесь. Пользовательские заголовки удаляются при перенаправлении на другой источник. Заголовки транспортного кадрирования переопределить нельзя.",
        "tr": "32 başlık ve 8 KiB'ye kadar. Content-Type veya Authorization'u burada ayarlayın. Farklı bir kaynağa yönlendirmelerde özel başlıklar kaldırılır. Taşıma çerçeveleme başlıkları geçersiz kılınamaz.",
        "zh-rCN": "最多 32 个标头和 8 KiB。在此设置 Content-Type 或 Authorization。重定向到其他源时会移除自定义标头。传输成帧标头无法覆盖。",
    },
    "Local network permission is needed only when private destinations are enabled": {
        "ar": "إذن الشبكة المحلية مطلوب فقط عند تمكين الوجهات الخاصة",
        "de": "Lokale Netzwerkberechtigung nur nötig, wenn private Ziele aktiviert sind",
        "es": "El permiso de red local solo es necesario si se activan destinos privados",
        "fr": "L'autorisation réseau local n'est nécessaire que si les destinations privées sont activées",
        "hi": "स्थानीय नेटवर्क अनुमति केवल तब आवश्यक जब निजी गंतव्य सक्षम हों",
        "ja": "ローカルネットワーク権限はプライベート宛先を有効にした場合のみ必要",
        "pt": "A permissão de rede local só é necessária se destinos privados estiverem ativados",
        "ru": "Разрешение локальной сети нужно только при включении частных адресов",
        "tr": "Yerel ağ izni yalnızca özel hedefler etkinleştirildiğinde gerekir",
        "zh-rCN": "仅当启用专用目标时才需要本地网络权限",
    },
    "HTTPS only. Enable this only for trusted services. Android 17 requires local network permission.": {
        "ar": "HTTPS فقط. فعّل هذا للخدمات الموثوقة فقط. يتطلب Android 17 إذن الشبكة المحلية.",
        "de": "Nur HTTPS. Nur für vertrauenswürdige Dienste aktivieren. Android 17 erfordert die lokale Netzwerkberechtigung.",
        "es": "Solo HTTPS. Actívalo solo para servicios de confianza. Android 17 requiere permiso de red local.",
        "fr": "HTTPS uniquement. À activer uniquement pour des services de confiance. Android 17 exige l'autorisation réseau local.",
        "hi": "केवल HTTPS। इसे केवल भरोसेमंद सेवाओं के लिए सक्षम करें। Android 17 को स्थानीय नेटवर्क अनुमति चाहिए।",
        "ja": "HTTPSのみ。信頼できるサービスのみ有効にしてください。Android 17ではローカルネットワーク権限が必要です。",
        "pt": "Somente HTTPS. Ative apenas para serviços confiáveis. O Android 17 exige permissão de rede local.",
        "ru": "Только HTTPS. Включайте только для доверенных сервисов. Android 17 требует разрешения локальной сети.",
        "tr": "Yalnızca HTTPS. Bunu yalnızca güvenilir hizmetler için etkinleştirin. Android 17 yerel ağ izni gerektirir.",
        "zh-rCN": "仅限 HTTPS。仅对可信服务启用。Android 17 需要本地网络权限。",
    },
    "Galaxy Store": {
        "ar": "متجر Galaxy", "zh-rCN": "Galaxy 商店",
    },
}


def android_escape(text: str) -> str:
    """Escape for Android string resources (aapt rules)."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace("'", "\\'")


def apply() -> int:
    changed_files = 0
    replaced = 0
    for default_path in glob.glob("**/src/main/res/values/strings.xml", recursive=True):
        default_path = default_path.replace("\\", "/")
        if "/build/" in default_path:
            continue
        mod = default_path.split("/src/main/res")[0]
        base_dir = Path(default_path).parents[1]

        # Full English values from the default file (ET unescapes entities).
        root = ElementTree.parse(default_path).getroot()
        defaults = {el.get("name"): "".join(el.itertext()) for el in root.iter("string") if el.get("name")}

        for loc_dir in sorted(base_dir.glob("values-*")):
            loc = loc_dir.name[len("values-"):]
            file = loc_dir / "strings.xml"
            if not file.is_file():
                continue
            text = file.read_text(encoding="utf-8")
            original = text
            for name, en in defaults.items():
                tr = T.get(en, {}).get(loc)
                if tr is None:
                    continue
                # Replace only when the current value is still the exact
                # English copy (escaped or not in the raw XML).
                pat = re.compile(
                    r'(<string name="%s">)(.*?)(</string>)' % re.escape(name),
                    re.DOTALL,
                )
                def _sub(m: re.Match) -> str:
                    current = (
                        m.group(2)
                        .replace("&amp;", "&")
                        .replace("&lt;", "<")
                        .replace("\\'", "'")
                    )
                    if current != en:
                        return m.group(0)  # already translated; keep it
                    return m.group(1) + android_escape(tr) + m.group(3)
                text, n = pat.subn(_sub, text)
                replaced += n
            if text != original:
                file.write_text(text, encoding="utf-8")
                changed_files += 1
    print(f"FILES CHANGED: {changed_files}, STRINGS TRANSLATED: {replaced}")
    return 0


if __name__ == "__main__":
    raise SystemExit(apply())
