package com.nexaflow.core.rom

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Guards the Magisk module generated by [SystemAppInstaller]: the module id
 * must stay stable (removal + updates depend on it), and the whitelist must
 * cover exactly the privileged permissions that make deep ROM integration
 * work without per-command root.
 */
class SystemAppInstallerTest {

    @Test
    fun `module id is stable for removal and updates`() {
        // The module id is used by `magisk --remove-module <id>`; changing it
        // silently would leave orphan modules behind.
        assertEquals("nexaflow_system_integration", SystemAppInstaller.MODULE_ID)
    }

    @Test
    fun `whitelist xml covers the privileged permissions used by the engine`() {
        val whitelist = SystemAppInstaller.whitelistXml()
        // The package must be the app package.
        assertTrue(whitelist.contains("com.nexaflow.app"))
        // The privileged permissions that make deep ROM integration work
        // without per-command root must all be whitelisted.
        for (permission in listOf(
            "android.permission.WRITE_SECURE_SETTINGS",
            "android.permission.STATUS_BAR",
            "android.permission.MODIFY_PHONE_STATE",
            "android.permission.FORCE_STOP_PACKAGES",
            "android.permission.READ_LOGS"
        )) {
            assertTrue("missing whitelisted permission $permission", whitelist.contains(permission))
        }
    }

    @Test
    fun `module prop declares the stable module id`() {
        val prop = SystemAppInstaller.moduleProp()
        assertTrue(prop.startsWith("id=nexaflow_system_integration"))
        assertTrue(prop.contains("name=NexaFlow System Integration"))
        assertTrue(prop.contains("description="))
    }

    @Test
    fun `whitelist xml is well-formed with balanced tags`() {
        val whitelist = SystemAppInstaller.whitelistXml()
        val openCount = whitelist.count { it == '<' }
        val closeCount = whitelist.count { it == '>' }
        assertEquals("mismatched angle brackets", openCount, closeCount)
        assertTrue(whitelist.contains("<permissions>"))
        assertTrue(whitelist.contains("</permissions>"))
        assertTrue(whitelist.contains("<privapp-permissions"))
        assertTrue(whitelist.contains("</privapp-permissions>"))
    }
}
